import '../globals.css'
import dynamic from 'next/dynamic'
const Providers = dynamic(() => import("../../redux/provider"), {
ssr: false,
});
import GAComponent from '../../components/global/GAComponent';

export const metadata = {
  title: 'TryDos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
       <GAComponent/>

     <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
        <Providers>
           {children}
        </Providers>
        </body>
    

    </html>
  )
}
