/**
 * Every string the demo shows, by its English key.
 *
 * Why a list: the demo shell is a client component that is also rendered on
 * the server. The shared client `translateFunction` (utils/functions) loads its
 * tables asynchronously, so the server painted English while the browser
 * painted Arabic, and React threw the whole tree away on hydration. Instead the
 * /demo layout (a server component) looks these keys up once, with the
 * server's own tables (utils/server), and hands the few hundred bytes to the
 * shell. Server and browser then print the same words.
 *
 * `DemoKey` types every `t()` in the demo, so a new string that is not on this
 * list does not compile. Each key must also exist in all three
 * public/translations files — `pnpm lint` and `pnpm lint:i18n-parity` check that.
 */
export const DEMO_KEYS = [
  "Hide menu",
  "Device and browser info",
  "Change page colour",
  "Show test pictures",
  "Main",
  "Home",
  "Search",
  "Cart",
  "Chat",
  "Profile",
  "Back",
  "Man",
  "Women",
  "Children",
  "Electronic",
  "Search anything…",
  "Voice search",
  "Scan",
  "For you",
  "Empty",
  "Your cart is empty",
  "Items you add to your cart will show here",
  "No conversations yet",
  "Messages with sellers will show here",
  "Web",
  "lock",
  "client ID",
  "ID",
  "Enter Your Name !",
  "Enter Address !",
  "Add photo",
  "Setup your size profile",
  "To get smart recommendations that fit you.",
  "Setup size now",
  "Unverified account",
  "Tap verify, skip the line, and enjoy exclusive offers.",
  "Verify now",
  "Get trydos Business",
  "Start Your Business now",
  "action",
  "Orders",
  "Trydos Wallet",
  "Settings",
  "Terms & Conditions",
  "Legal Information",
  "About Us",
  "Share App",
  "Login history",
  "logout",
  "Profile Photo",
  "Cancel",
  "Add & save",
  "Choose",
  "Take Photo",
  "Remove",
  "Uploading profile photo …",
  "copy",
  "download",
  "share",
  "client name",
  "client Phone Number",
  "client Info",
  "Personal Info",
  "Body measurements",
  "Address",
  "client Information",
  "client Status",
  "client since",
  "client type",
  "client Verified",
  "Active",
  "days",
  "Personal",
  "Verified",
  "Change my Phone Number Request",
  "Delete my account Request",
  "Edit",
  "full Name",
  "Enter Full Name",
  "Email",
  "enter Email Address",
  "Gender",
  "Other",
  "verification Email !",
  "enter verification code sent to your Email",
  "resend after",
  "Your privacy is completely safe",
  "How tall are you?",
  "What is your weight?",
  "What is your Foot size?",
  "000 CM",
  "000 KG",
  "Add Shipping Address",
  "Delete",
  "Your address list is empty",
  "You can also create multiple addresses to use",
  "Close",
  "Delete below address ?",
  "Sure, Delete",
  "Turkiye",
  "Syria",
  "Iraq",
  "Lebanon",
  "Country | Region",
  "Select from list",
  "Detailed address",
  "Street address, building, Flat, Door, unit.",
  "Address title",
  "Ex: Home, my office, 2 home ect.",
  "your location on map",
  "Locate your location on map",
  "location is accurate, making it easy to receive shipments",
  "Select",
  "Province",
  "District",
  "Town",
  "Street",
  "Search Province | District | Town | Street",
  "Entering your information correctly allows us to provide you with better service and benefit from all services.",
  "Why add a address?",
  "Accurate address details ensure faster delivery of your correct products and show you the best options in your area.",
  "Learn more",
  "Trydos Balance",
  "your total balance",
  "your total USD balance",
  "your total SYP balance",
  "Amerikan dollars",
  "syrian pounds",
  "All Transactions",
  "All USD Transactions",
  "All SYP Transactions",
  "Cash Deposit",
  "Cash Withdrawal",
  "Order Invoice Payment",
  "Refund Order",
  "Cash in request",
  "Success",
  "Blocked",
  "Waiting Due in",
  "Cash In",
  "Cash Out",
  "You can withdraw your money through the following options easily and securely.",
  "Recommended",
  "Easy . Fast . No commission",
  "Withdraw your funds !",
  "You can withdraw your funds with complete ease through one of our Trydos & RDB centers. You can also withdraw your funds to your personal account on RDB.",
  "Available branches",
  "More Info",
  "To My {bank}",
  "recipient",
  "Trydos client phone number",
  "Trydos client Full name ( Exact ID )",
  "Add",
  "Authorized recipient",
  "Enter withdrawal amount",
  "Available",
  "Sham Cash",
  "Syriatel Cash",
  "Irsal",
  "Wallet Info",
  "request",
  "Trydos client Name",
  "Trydos client ID",
  "Trydos client Phone Number",
  "receipt",
  "Date & time",
  "reference",
  "amount",
  "type",
  "Status",
  "succeeded",
  "Sender",
  "Receiver",
  "receive",
  "wallet",
  "Enter Amount",
  "Your Balance is insufficient",
  "Authorized recipient phone number",
  "Authorized recipient Full name ( Exact ID )",
  "Enter {field}",
  "Edit {field}",
  "Enter recipient Phone number",
  "Only the named person may receive the amount !",
  "Withdrawal Request",
  "Withdrawal Now",
  "Read the code on the opposite side to take action",
  "Cash withdraw",
  "Please read the code in front of you at the {brand} center, then receive the amount from the employee.",
  "Do not leave the page or the center until you have confirmed that the transaction is complete.",
  "Thank you.",
  "verification !",
  "enter verification code sent to your WhatsApp",
  "Authorized recipient Full name",
  "Your Withdrawal Request Ready to Collect !",
  "Present this code along with your personal ID at any of our branches and receive the amount in complete security.",
  "Thank you",
  "we are pleased to serve you",
  "{bank} client ID",
  "{bank} client phone number",
  "{bank} client Full name (Exact ID)",
  "Enter withdrawal amount to your {bank}",
  "Withdrawal To {bank}",
  "American dollars",
  "We have sent a verification code to the number",
  "You can add funds to an account through the following options easily and securely.",
  "Soon available",
  "Add funds !",
  "You can deposit your funds with complete ease through one of our Trydos & RDB centers. You can also deposit your funds into your personal account on RDB. Additionally, any person or another account can add funds to your account.",
  "From My {bank}",
  "Deposit",
  "Enter requested amount from your {bank}",
  "Connect & request from your {bank}",
  "Enter requested amount",
  "Via crypto",
  "We will charge {charge} {coin} for topping up your balance {amount} {code}.",
  "You will pay {charge} {network} to generated wallet",
  "We will send to your Trydos balance {amount} {code}",
  "Generate QR code",
  "Your transactions are safe",
  "Send the exact amount to complete your transaction",
  "The entire amount must be sent at once or in parts according to the specified period.",
  "You can send the amount from different addresses on the same network and the same selected currency.",
  "Send the selected currency to complete your transaction",
  "The transaction must be sent in the same currency selected, otherwise the transaction will be suspended.",
  "However, if the transaction was made by mistake, contact customer support to start the refund process.",
  "Transaction must be sent within the specified period.",
  "After the expiry of the period, the transaction will be suspended. Contact customer support.",
  "Do not transfer to the same address on your own.",
  "The address used is temporary and does not mean that the current address is specific to you.",
  "I agree",
  "I disagree & cancel",
  "{amount} {coin} deposit",
  "Scan QR code from your wallet & pay to start processing",
  "Within {time} minutes",
  "Or try direct link to",
  "After the specified period has expired, do not transfer any amount. Request a new QR code.",
  "Expiry {date} | {time}",
  "The wallet above is linked to a payment to a specific account !",
  "So once the payment is completed, the balance will be added automatically. It is considered a one-time-use wallet only",
  "Your deposit request ready to collect !",
  "Present this code along with your personal ID at any of our branches and pay the amount in complete security.",
] as const;

export type DemoKey = (typeof DEMO_KEYS)[number];

export type DemoDictionary = Partial<Record<DemoKey, string>>;
