/**
 * Every string the demo shows, by its English key.
 *
 * Why a list: the demo shell is a client component that is also rendered on
 * the server. The shared client `translateFunction` (utils/functions) loads its
 * tables asynchronously, so the server painted English while the browser
 * painted Arabic, and React threw the whole tree away on hydration. Instead the
 * /demo layout (a server component) looks these keys up once, with the
 * server's own tables (utils/server), and hands the few hundred bytes to the
 * shell. Server and browser then print the same words.
 *
 * `DemoKey` types every `t()` in the demo, so a new string that is not on this
 * list does not compile. Each key must also exist in all three
 * public/translations files — `pnpm lint` and `pnpm lint:i18n-parity` check that.
 */
export const DEMO_KEYS = [
  "Hide menu",
  "Device and browser info",
  "Main",
  "Home",
  "Search",
  "Cart",
  "Chat",
  "Profile",
  "Back",
  "Man",
  "Women",
  "Children",
  "Electronic",
  "Search anything…",
  "Voice search",
  "Scan",
  "For you",
  "Empty",
  "Your cart is empty",
  "Items you add to your cart will show here",
  "No conversations yet",
  "Messages with sellers will show here",
  "Web",
  "lock",
  "client ID",
  "ID",
  "Enter Your Name !",
  "Enter Address !",
  "Add photo",
  "Setup your size profile",
  "To get smart recommendations that fit you.",
  "Setup size now",
  "Unverified account",
  "Tap verify, skip the line, and enjoy exclusive offers.",
  "Verify now",
  "Get trydos Business",
  "Start Your Business now",
  "action",
  "Orders",
  "Trydos Wallet",
  "Settings",
  "Terms & Conditions",
  "Legal Information",
  "About Us",
  "Share App",
  "Login history",
  "logout",
  "Profile Photo",
  "Cancel",
  "Add & save",
  "Choose",
  "Take Photo",
  "Remove",
  "Uploading profile photo …",
  "copy",
  "download",
  "share",
  "client name",
  "client Phone Number",
  "client Info",
  "Personal Info",
  "Body measurements",
  "Address",
  "client Information",
  "client Status",
  "client since",
  "client type",
  "client Verified",
  "Active",
  "days",
  "Personal",
  "Verified",
  "Change my Phone Number Request",
  "Delete my account Request",
  "Edit",
  "full Name",
  "Enter Full Name",
  "Email",
  "enter Email Address",
  "Gender",
  "Other",
  "verification Email !",
  "enter verification code sent to your Email",
  "resend after",
  "Your privacy is completely safe",
  "How tall are you?",
  "What is your weight?",
  "What is your Foot size?",
  "000 CM",
  "000 KG",
  "Add Shipping Address",
  "Delete",
  "Your address list is empty",
  "You can also create multiple addresses to use",
  "Close",
  "Delete below address ?",
  "Sure, Delete",
  "Turkiye",
  "Syria",
  "Iraq",
  "Lebanon",
  "Country | Region",
  "Select from list",
  "Detailed address",
  "Street address, building, Flat, Door, unit.",
  "Address title",
  "Ex: Home, my office, 2 home ect.",
  "your location on map",
  "Locate your location on map",
  "location is accurate, making it easy to receive shipments",
  "Select",
  "Province",
  "District",
  "Town",
  "Street",
  "Search Province | District | Town | Street",
  "Entering your information correctly allows us to provide you with better service and benefit from all services.",
  "Why add a address?",
  "Accurate address details ensure faster delivery of your correct products and show you the best options in your area.",
  "Learn more",
] as const;

export type DemoKey = (typeof DEMO_KEYS)[number];

export type DemoDictionary = Partial<Record<DemoKey, string>>;
