stages:
  - build and deploy
  - test

deploy-to-vercel:
  stage: build and deploy
  image: node:20.9.0

  script:
    - yarn
    - npx next build

cypress_test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test

  script:
    - yarn
    - npm run test

  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/reports
