stages:
  - deploy
  - test

deploy-to-vercel:
  stage: deploy
  image: node:20.0.0

  script:
    - echo $VERCEL_TOKEN
    - npm i -g vercel
    - vercel --token RxBPi4PALYovZWQxdtbXQmAM > vercel_deployment_url.txt

  artifacts:
    when: on_success
    paths:
      - vercel_deployment_url.txt

cypress_test:
  image: cypress/browsers:node12.16.2-chrome81-ff75
  stage: test

  script:
    - DEPLOYMENT_URL=$(cat vercel_deployment_url.txt)
    - npm i
    - npm ci
    - $(npm bin)/cypress run --env CYPRESS_BASE_URL=$DEPLOYMENT_URL+`/tr-en`

  artifacts:
    when: on_success
    paths:
      - cypress/screenshots
      - cypress/videos