let sample = {
  id: 2,
  name: "Short-Sleeve Woven Blouse",
  user_id: 80,
  added_by: "admin",
  unit: "pc",
  tags_ids: [],
  countries_iso: [],
  images:
    '["2025-05-11-682071cde3e92.png","2025-05-11-682071d192306.png","2025-05-11-682071d56b048.png","2025-05-11-682071dca4694.png","2025-05-11-682071e065903.png"]',
  brand_id: 8,
  boutique_id: 1,
  thumbnail: {
    file_path: "/product/2025-05-11-682071cde3e92.png",
    original_width: "246",
    original_height: "500",
  },
  text_colors: '["#FFFFFF"]',
  colors: [
    {
      id: 117,
      name: "White",
      color: "#FFFFFF",
    },
  ],
  similar_words_colors: [
    "white",
    "whites",
    "snow",
    "ivory",
    "milky",
    "pearl",
    "vanilla",
    "alabaster",
    "bone",
    "chalk",
    "cream",
    "frost",
    "ghost",
    "lily",
    "paper",
    "porcelain",
    "seashell",
    "silver",
    "whight",
    "wite",
    "wit",
    "beyaz",
    "ak",
    "biaz",
    "beyas",
    "beyazz",
    "akça",
    "pak",
    "nefti",
    "gümüşi",
    "sedefi",
    "elfenbeği",
    "fildişi",
    "inci",
    "vanilya",
    "krem",
    "açık",
    "أبيض",
    "ابيض",
    "الابيض",
    "ابيضاض",
    "ناصع",
    "باهت",
    "لامع",
    "ثلجي",
    "ثَلْجِيّ",
    "فاتح",
    "زاهي",
    "أمهق",
    "أَصْفَرُ_بَاهِت",
    "شاحب",
    "ساطع",
    "نصوع",
  ],
  sync_color_images:
    '[{"color_name":"Pink","images":["2025-05-11-682071cde3e92.png","2025-05-11-682071d56b048.png","2025-05-11-682071d192306.png"],"color_trend":null},{"color_name":"White","images":["2025-05-11-682071e065903.png","2025-05-11-682071dca4694.png","2025-05-11-682071d906804.png"],"color_trend":null}]',
  attributes: '["1"]',
  available_size: '["XL","L","M"]',
  similar_words_sizes: [
    "XL",
    "X-Large",
    "ExtraL",
    "XtraL",
    "ExL",
    "eXtraLarge",
    "eXtra-Large",
    "eXtraL",
    "eX-Large",
    "eXLarge",
    "XLarge",
    "EkstraBüyük",
    "EkstraBuyuk",
    "Ekstra",
    "X",
    "Large",
    "Büyük",
    "Buyuk",
    "ÇokBüyük",
    "CokBuyuk",
    "اكس",
    "اكسل",
    "xlarge",
    "اكس_لارج",
    "كبير_جدا",
    "كبيره_جدا",
    "ك_جدا",
    "كبير_جداً",
    "كبيره_جداً",
    "ك_جداً",
    "M",
    "Med",
    "Medium",
    "m",
    "orta",
    "Orta",
    "medyum",
    "Mediyum",
    "Midi",
    "midi",
    "M beden",
    "m beden",
    "orta beden",
    "Orta beden",
    "م",
    "وسط",
    "متوسط",
    "ميديوم",
    "ميديم",
    "وسطى",
    "مت",
    "med",
    "mid",
    "medium",
    "L",
    "Larege",
    "Larj",
    "El",
    "l",
    "Larc",
    "Buyukkk",
    "Byk",
    "byk",
    "BÜYÜK",
    "Buyukk",
    "Büyükk",
    "Geniş",
    "Genis",
    "جنش",
    "ل",
    "لارج",
    "لارغ",
    "كبير",
    "ك",
    "kebir",
    "larj",
    "laarj",
    "kabir",
  ],
  available_size_as_json: [
    {
      size: "XL",
    },
    {
      size: "L",
    },
    {
      size: "M",
    },
  ],
  unit_price: 7,
  offered_price: 4.600000000000019,
  purchase_price: 3,
  discount: "34.285714285714",
  discount_type: "percent",
  redeem_discount_rate: 57.142857142857,
  redeem_price: 3,
  current_stock: "7.000",
  details:
    "<p>Amazon Essentials Women&#39;s Relaxed-Fit Short-Sleeve Woven Blouse</p>",
  status: 1,
  flash_deal_max_allowed_quantity: 0,
  featured: "1",
  flash_deal: null,
  created_at: "2025-05-11T09:46:16.000000Z",
  updated_at: "2025-07-15T17:33:34.000000Z",
  category_ids: [
    {
      id: "2",
      position: 1,
    },
    {
      id: "7",
      position: 2,
    },
  ],
  tags_names: [],
  brand: {
    id: 8,
    name: "zara",
    status: 1,
    countries_iso: [],
  },
  custom_brands: [
    {
      id: 22,
      brand_id: 8,
      language_code: "en",
      country_iso: null,
      name: "zara",
      similar_words:
        '["zara","zahra","zarah","zaras","zaraa","zarra","zaras","zaara","zaraa","zera","zarahemla","zahraa","zar","zahr","zaar","zarra"]',
      slug: "zara-22",
      icon: {
        file_path: "/brand/2025-05-11-68206cd78901f.svg",
        original_width: "1000",
        original_height: "420.62616",
      },
      created_at: "2025-05-11T09:24:44.000000Z",
      updated_at: "2025-06-13T07:14:52.000000Z",
      added_by_type: 2,
      added_by_id: 78,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
    },
    {
      id: 23,
      brand_id: 8,
      language_code: "tr",
      country_iso: null,
      name: "zara",
      similar_words:
        '["zara","zaraa","zarra","zara\'a","sara","zaraa","zaara","zaras","zarra","zaza","zraa","zaraı","zraa","zaara","zeara","zerra","zala","jara"]',
      slug: "zara-23",
      icon: {
        file_path: "/brand/2025-05-11-68206cdc3ca01.svg",
        original_width: "1000",
        original_height: "420.62616",
      },
      created_at: "2025-05-11T09:24:48.000000Z",
      updated_at: "2025-06-13T07:13:13.000000Z",
      added_by_type: 2,
      added_by_id: 78,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
    },
    {
      id: 24,
      brand_id: 8,
      language_code: "ar",
      country_iso: null,
      name: "زارا",
      similar_words:
        '["زارا","زاره","ذارا","ذاره","زاراء","زرا","ذرا","زارهه","ذارهه","زاري","ذاري","زاراh","زاراa","ذاراh","ذاراa","زراa","ذراa","زارا_","زرا_","ذرا_","ذارا_","زاره_","ذاره_"]',
      slug: "زارا-24",
      icon: {
        file_path: "/brand/2025-05-11-68206ce0a75ee.svg",
        original_width: "1000",
        original_height: "420.62616",
      },
      created_at: "2025-05-11T09:24:53.000000Z",
      updated_at: "2025-06-13T07:13:15.000000Z",
      added_by_type: 2,
      added_by_id: 78,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
    },
  ],
  custom_boutiques: [
    {
      id: 1,
      boutique_id: 1,
      category_id: null,
      language_code: "en",
      country_iso: null,
      slug: "womens-fashion-1",
      name: "Women's fashion",
      description: "<p>Women&#39;s fashion</p>",
      icon: {
        file_path: "/boutiques/boutiques/icon/2025-05-11-682063a3ec4d9.svg",
        original_width: "800px",
        original_height: "800px",
      },
      bio: "<p>Women&#39;s fashion</p>",
      created_at: "2025-05-11T08:45:40.000000Z",
      updated_at: "2025-05-11T08:45:40.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      banners: [
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063a8f07e8.jpg",
          original_width: "1920",
          original_height: "864",
          deleted_at: null,
        },
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063ad28606.avif",
          original_width: "740",
          original_height: "425",
          deleted_at: null,
        },
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063b0db6bd.avif",
          original_width: "740",
          original_height: "343",
          deleted_at: null,
        },
      ],
    },
    {
      id: 2,
      boutique_id: 1,
      category_id: null,
      language_code: "ar",
      country_iso: null,
      slug: "azyaaa-nsayy-2",
      name: "أزياء نسائية",
      description: "<p>أزياء نسائية</p>",
      icon: {
        file_path: "/boutiques/boutiques/icon/2025-05-11-682063b4b1b13.svg",
        original_width: "800px",
        original_height: "800px",
      },
      bio: "<p>أزياء نسائية</p>",
      created_at: "2025-05-11T08:45:57.000000Z",
      updated_at: "2025-05-26T12:02:54.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      banners: [
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063b9ba529.jpg",
          original_width: "1920",
          original_height: "864",
          deleted_at: null,
        },
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063bdaeabb.avif",
          original_width: "740",
          original_height: "425",
          deleted_at: null,
        },
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063c15f0ed.avif",
          original_width: "740",
          original_height: "343",
          deleted_at: null,
        },
      ],
    },
    {
      id: 3,
      boutique_id: 1,
      category_id: null,
      language_code: "tr",
      country_iso: null,
      slug: "kadin-modasi-3",
      name: "Kadın modası",
      description: "<p>Kadın modası</p>",
      icon: {
        file_path: "/boutiques/boutiques/icon/2025-05-11-682063c531765.svg",
        original_width: "800px",
        original_height: "800px",
      },
      bio: "<p>Kadın modası</p>",
      created_at: "2025-05-11T08:46:13.000000Z",
      updated_at: "2025-05-26T12:02:57.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      banners: [
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063c9e272d.jpg",
          original_width: "1920",
          original_height: "864",
          deleted_at: null,
        },
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063cdd7796.avif",
          original_width: "740",
          original_height: "425",
          deleted_at: null,
        },
        {
          file_path: "/boutiques/boutiques/2025-05-11-682063d1ada16.avif",
          original_width: "740",
          original_height: "343",
          deleted_at: null,
        },
      ],
    },
  ],
  boutique: {
    id: 1,
    seller_id: null,
    name: "Women's fashion",
    position: 0,
    status: 0,
    countries_iso: [],
    added_by_type: 2,
    added_by_id: 80,
  },
  custom_products: [
    {
      id: 4,
      product_id: 2,
      language_code: "en",
      country_iso: null,
      name: "Short-Sleeve Woven Blouse",
      similar_words: [
        "Short Sleeve Woven Blouse",
        "Short-Sleeve Woven Blouses",
        "Short Sleeve Woven Blouses",
        "Short-Sleeve Blouse",
        "Short Sleeve Blouse",
        "Woven Blouse Short-Sleeve",
        "Woven Blouse Short Sleeve",
        "Woven Short-Sleeve Blouse",
        "Woven Short Sleeve Blouse",
        "Blouse Short-Sleeve Woven",
        "Blouse Short Sleeve Woven",
        "Short Sleeved Woven Blouse",
        "Short-Sleeved Woven Blouse",
        "Short Sleeved Blouses",
        "Short-Sleeved Blouses",
        "Woven Short Sleeve Blouses",
        "Woven Short-Sleeve Blouses",
      ],
      slug: "short-sleeve-woven-blouse-4",
      old_slugs: null,
      details:
        "<p>A comfortable and stylish top, perfect for warm weather. This blouse features short sleeves and is made from a woven fabric.</p>",
      tags_names: null,
      descriptors_names: "silk-soft cotton-soft cotton",
      label_names: ["high quality", "suitable of summer", "Great for vacation"],
      status: 1,
      created_at: "2025-05-11T09:47:07.000000Z",
      updated_at: "2025-07-05T05:43:34.000000Z",
      deleted_at: null,
      added_by: 2,
      is_has_to_translate_with_AI: 0,
    },
    {
      id: 5,
      product_id: 2,
      language_code: "tr",
      country_iso: null,
      name: "Kısa Kollu Dokuma Bluz",
      similar_words: [
        "Kısa Kollu Dokuma Bluz",
        "Kisa Kollu Dokuma Bluz",
        "Kısa Kol Dokuma Bluz",
        "Kisa Kol Dokuma Bluz",
        "Kısa Kollu Bluz",
        "Kisa Kollu Bluz",
        "Dokuma Bluz Kısa Kollu",
        "Dokuma Bluz Kisa Kollu",
        "Bluz Kısa Kollu",
        "Bluz Kisa Kollu",
        "Kısa Kollu Dokuma",
        "Kisa Kollu Dokuma",
        "Dokuma Kısa Kollu Bluz",
        "Dokuma Kisa Kollu Bluz",
        "Kısa Kol Dokuma",
        "Kisa Kol Dokuma",
        "Dokuma Kısa Kol Bluz",
        "Dokuma Kisa Kol Bluz",
        "Kısa Kol Bluz",
        "Kisa Kol Bluz",
      ],
      slug: "kisa-kollu-dokuma-bluz-5",
      old_slugs: null,
      details:
        "<p>Kısa kollu dokuma bluz, sıcak havalarda serin ve şık kalmak i&ccedil;in m&uuml;kemmel bir se&ccedil;enektir. Hafif ve nefes alabilen dokuma kumaştan &uuml;retilmiştir ve rahat bir kesime sahiptir. G&uuml;nl&uuml;k kullanım i&ccedil;in idealdir ve &ccedil;eşitli stillerle kolayca kombinlenebilir.</p>",
      tags_names: null,
      descriptors_names: "Abramoviç Nasır-pamuk",
      label_names: ["yüksek kaliteli", "yaza uygun", "Tatil için harika"],
      status: 1,
      created_at: "2025-05-11T09:47:07.000000Z",
      updated_at: "2025-07-05T05:43:36.000000Z",
      deleted_at: null,
      added_by: 2,
      is_has_to_translate_with_AI: 0,
    },
    {
      id: 6,
      product_id: 2,
      language_code: "ar",
      country_iso: null,
      name: "بلوزة منسوجة بأكمام قصيرة",
      similar_words: [
        "بلوزة منسوجة بأكمام قصيرة",
        "بلوزة باكمام قصيرة",
        "بلوزة باكمام قصيره",
        "بلوزة منسوجة اكمام قصيرة",
        "بلوزة منسوجة بأكمام قصيره",
        "بلوزه منسوجة بأكمام قصيرة",
        "بلوزة منسوجة باكمام قصيرة",
        "بلوزه منسوجه باكمام قصيرة",
        "بلوزة بكم قصير",
        "بلوزة بأكمام",
        "بلوزه باكمام قصيره",
        "بلوزه باكمام قصيره",
        "بلوزة",
        "بلوزه",
      ],
      slug: "bloz-mnsog-bakmam-ksyr-6",
      old_slugs: null,
      details:
        "<p>بلوزة منسوجة بأكمام قصيرة هي قطعة ملابس أنيقة وعملية ومثالية للارتداء في الطقس الدافئ. تتميز بتصميم مريح وأنيق، مما يجعلها مناسبة لمختلف المناسبات.</p>",
      tags_names: null,
      descriptors_names: "حرير-قطن",
      label_names: ["جودة عالية", "ملائم لفصل الصيف", "مثال لقضاء العطلات"],
      status: 1,
      created_at: "2025-05-11T09:47:07.000000Z",
      updated_at: "2025-07-05T05:43:38.000000Z",
      deleted_at: null,
      added_by: 2,
      is_has_to_translate_with_AI: 0,
    },
    {
      id: 653,
      product_id: 2,
      language_code: "ku",
      country_iso: null,
      name: "Blûza Tevnî ya Destkurt",
      similar_words: [
        "Blûza Tevnî ya Destkurt",
        "Blûz Tevnî ya Destkurt",
        "Blûza Tevni ya Destkurt",
        "Blûz Tevni ya Destkurt",
        "Blusa Tevnî ya Destkurt",
        "Blus Tevnî ya Destkurt",
        "Blusa Tevni ya Destkurt",
        "Blus Tevni ya Destkurt",
        "Bluz Tevnî ya Destkurt",
        "Bluz Tevni ya Destkurt",
        "Blûzên Tevnî ya Destkurt",
        "Blûzên Tevni ya Destkurt",
        "Blusên Tevnî ya Destkurt",
        "Blusên Tevni ya Destkurt",
        "Bluzen Tevnî ya Destkurt",
        "Bluzen Tevni ya Destkurt",
      ],
      slug: "bluza-tevni-ya-destkurt-653",
      old_slugs: null,
      details:
        "<p>Blûza Tevnî ya Destkurt a Fit Relaxed a Amazon Essentials Women&#39;s.</p>",
      tags_names: null,
      descriptors_names: null,
      label_names: null,
      status: 1,
      created_at: "2025-07-05T17:00:06.000000Z",
      updated_at: "2025-07-05T17:00:10.000000Z",
      deleted_at: null,
      added_by: 10,
      is_has_to_translate_with_AI: 0,
    },
  ],
  categories: [
    {
      id: 2,
      name: "women's fashion",
      parent_id: 0,
      position: 0,
      status: 1,
      num_available_product: 22,
      countries_iso: [],
    },
    {
      id: 7,
      name: "Blouses",
      parent_id: 2,
      position: 1,
      status: 1,
      num_available_product: 6,
      countries_iso: [],
    },
  ],
  custom_categories: [
    {
      id: 4,
      category_id: 2,
      language_code: "en",
      country_iso: null,
      name: "women's fashion",
      similar_words:
        '["womens","women","fashion","clothing","clothes","apparel","style","wear","dresses","skirts","tops","pants","jeans","shoes","accessories","womenswear","ladies","ladieswear","chic","trendy","stylish","outfits","glamour","couture","vogue","mode","attire","garments","threads","rags","sartorial","couturier","designs","elegance","femme","feminine","modern","classic","vintage","retro","boho","casual","formal","workwear","activewear","loungewear","basics","petite","plus","maternity","seasonal","summer","winter","spring","autumn","fall","collection","wardrobe","ensemble","look","glam","dress","skirt","top","trouser","shirt","blouse","sweater","jacket","coat","blazer","cardigan","jumper","vest","corset","lingerie","swimwear","hosiery","socks","leggings","tights","scarf","gloves","hats","jewelry","bags","handbags","purses","wallets","belts","watches","sunglasses","eyewear","footwear"]',
      slug: "womens-fashion-4",
      bio: "<p>women fashion</p>",
      description: "<p>women fashion</p>",
      flat_photo_path: {
        file_path: "/category/2025-05-11-682064cb01b7f.svg",
        original_width: "800px",
        original_height: "800px",
      },
      outline_photo_path: {
        file_path: "/category/2025-05-11-682064d4728c2.svg",
        original_width: "800px",
        original_height: "800px",
      },
      png_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      fill_photo_path: {
        file_path: "/category/2025-05-11-682064cfa8fc8.svg",
        original_width: "800px",
        original_height: "800px",
      },
      banner_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      created_at: "2025-05-11T08:50:33.000000Z",
      updated_at: "2025-06-13T07:41:07.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      status: 1,
      position: 0,
    },
    {
      id: 5,
      category_id: 2,
      language_code: "ar",
      country_iso: null,
      name: "ازياء نسائية",
      similar_words:
        '["موضة","اناقة","جمال","بنات","حريمي","نسائي","صبايا","بناتي","فاشن","ملابس","اكسسوارات","ميكياج","مكياج","ازياء","موضه","ملبوسات","لباس","ستايل","تسوق","تجميل","انوثة","مراهقات","حريم","صبايا","انثوي","فستان","فساتين","تنورة","تنانير","قميص","بدي","بلايز","بلوزة","بنطلون","جينز","شورت","عباية","عبايات","جلابية","جلابيات","كاجوال","رسمي","سهرة","سهرات","حفلات","حفلة","خروج","طلعة","بجامة","بيجامة","لانجري","داخلية","جوارب","حقائب","شنط","احذية","جزمة","صندل","اكسسوار","مجوهرات","ذهب","فضة","الماس","نظارات","ساعات","موضه_بنات","فاشن_بنات","ميك_اب","ميكاب","ايلاينر","روج","بودرة","كريم","بشرة","شعر","اظافر","طلاء","مانكير","بيديكير","صالون","تصفيف","قصة","صبغة","بروتين","كيراتين","زيوت","شامبو","بلسم","حناء","عروس","عرس","خطوبة","زفاف","ملكة","حفلة_تخرج"]',
      slug: "azyaaa-nsayy-5",
      bio: "<p>أزياء نسائية&nbsp;</p>",
      description: "<p>أزياء نسائية&nbsp;</p>",
      flat_photo_path: {
        file_path: "/category/2025-05-11-682064d98b2b8.svg",
        original_width: "800px",
        original_height: "800px",
      },
      outline_photo_path: {
        file_path: "/category/2025-05-11-682064e3a3f4a.svg",
        original_width: "800px",
        original_height: "800px",
      },
      png_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      fill_photo_path: {
        file_path: "/category/2025-05-11-682064dee2f61.svg",
        original_width: "800px",
        original_height: "800px",
      },
      banner_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      created_at: "2025-05-11T08:50:48.000000Z",
      updated_at: "2025-06-13T07:41:12.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      status: 1,
      position: 0,
    },
    {
      id: 6,
      category_id: 2,
      language_code: "tr",
      country_iso: null,
      name: "kadın moda",
      similar_words:
        '["kadın","kadin","moda","giyim","elbise","butik","trend","tarz","stil","bayangiyim","bayan","kıyafet","kiyafet","elbiseler","modası","kombin","kombinler","abiye","tesettür","esarp","eşarp","şal","sal","triko","bluz","gomlek","gömlek","pantolon","etek","ceket","hırka","hirka","mont","kaban","pardösü","pijama","içgiyim","icgiyim","çamaşır","camasir","çorap","corap","aksesuar","takı","taki","ayakkabı","ayakkabi","canta","çanta","spor","günlük","gunluk","gece","mezuniyet","davet","özeltasarım","ozeltasarim","indirim","kampanya","yenisezon","yenisezon","klasik","modern","vintage","retro","bohem","casual","şık","sik","marka","design","tasarim","özel","ozel","pamuk","kumaş","kumas","deri","ipek","tül","tul","yün","yun","keten","viskon","likra","polyester","modal","trendler","modeller","stiller","kadınlar","bayanlar","giysiler","kiyafetler"]',
      slug: "kadin-moda-6",
      bio: "<p>kadın moda</p>",
      description: "<p>kadın moda</p>",
      flat_photo_path: {
        file_path: "/category/2025-05-11-682064e8cdc15.svg",
        original_width: "800px",
        original_height: "800px",
      },
      outline_photo_path: {
        file_path: "/category/2025-05-11-682064f2d9dbe.svg",
        original_width: "800px",
        original_height: "800px",
      },
      png_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      fill_photo_path: {
        file_path: "/category/2025-05-11-682064ed82959.svg",
        original_width: "800px",
        original_height: "800px",
      },
      banner_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      created_at: "2025-05-11T08:51:08.000000Z",
      updated_at: "2025-06-13T07:41:16.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      status: 1,
      position: 0,
    },
    {
      id: 19,
      category_id: 7,
      language_code: "en",
      country_iso: null,
      name: "Blouses",
      similar_words:
        '["blouse","tops","shirts","shirts","clothing","clothes","top","shirt","blouses","blous","bluss","blouss","blose","blooses","blaus","blawse","womans","womens","ladies","ladiess","lady","tee","tees","tshirt","tshirts","tee-shirt","tee-shirts","t","ts","cloths","garment","garments","apparels","apparel","dress","dresses","wear","wears","fashion","style","attire","chic","trendy","stylish","smart","casual","formal","workwear","office","evening","party","summer","winter","autumn","spring","cotton","silk","linen","polyester","rayon","crepe","chiffon","jersey","denim","flannel","velvet","twill","satin","poplin","voile","lace","knit","knits","weaves","woven","printed","embroidered","plain","patterned","striped","floral","checkered","dotted","sleeves","sleeve","sleeveless","short","long","collared","collarless","buttoned","neck","vneck","round","square","scoop","halter","turtleneck"]',
      slug: "blouses-19",
      bio: "<p>Blouses</p>",
      description: "<p>Blouses</p>",
      flat_photo_path: {
        file_path: "/category/2025-05-11-68206c03e477e.svg",
        original_width: "800px",
        original_height: "800px",
      },
      outline_photo_path: {
        file_path: "/category/2025-05-11-68206c0cee2e4.svg",
        original_width: "800px",
        original_height: "800px",
      },
      png_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      fill_photo_path: {
        file_path: "/category/2025-05-11-68206c08b06df.svg",
        original_width: "800px",
        original_height: "800px",
      },
      banner_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      created_at: "2025-05-11T09:21:22.000000Z",
      updated_at: "2025-06-13T07:41:50.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      status: 1,
      position: 1,
    },
    {
      id: 20,
      category_id: 7,
      language_code: "ar",
      country_iso: null,
      name: "بلوزات",
      similar_words:
        '["بلوزة","بلوزات","بلوز","بلايز","بلوزه","بلوزة_نسائية","قمصان","ملابس","توبات","بديات","بلوزات_بنات","بلوزات_حريمي","بدي","قماش","خامة","موضة","ازياء","لبس","ستايل","بناطيل","تنورات","جيليهات","كارديجان","جاكيتات","معاطف","ملابس_نسائية","بلوزات_صيفي","بلوزات_شتوي","بلوزه_صيفي","بلوزه_شتوي","بلوفرات","كنزات","تيشرتات","تيشيرت","قميص","قميص_نسائي","بلوزات_رسمية","بلوزات_كاجوال","بلوزة_رسمية","بلوزة_كاجوال","بلوزات_قطنية","قطن","حرير","صوف","بلوزات_حريرية","بلوزات_صوفية","فساتين","فستان","بلوزات_سهرة","بلوزة_سهرة","بلوزه_سهره","بلوزات_مناسبات","بلوزة_مناسبات","بلوزه_مناسبه","بلوزات_أنيقة","بلوزة_أنيقة","انيقة","بلوفر","توب","موضه","الوان","مقاسات","بلوزات_مقاس_كبير","بلوزة_مقاس_كبير","كبير","صغير","وسط","بلوزات_بناتي","بناتي","حريمي","نسائي","بنات","حريم","نساء","بنت","حرمة","مراهقات","اطفال","بلوزات_اطفال","بلوزه_بنات","بلوزه_اطفال","بلوزات_شتويه","بلوزة_شتويه","بلوزات_صيفيه","بلوزة_صيفيه","بلوزات_راقية","راقية","بلوزات_فخمة","فخمة","كشخة","بلوفرات_نسائية","كنزات_نسائية","بلوزات_ناعمة","ناعمة","بلوزة_ناعمة","بلوزات_مريحة","مريحة"]',
      slug: "blozat-20",
      bio: "<p>بلوزات</p>",
      description: "<p>بلوزات</p>",
      flat_photo_path: {
        file_path: "/category/2025-05-11-68206c124ba18.svg",
        original_width: "800px",
        original_height: "800px",
      },
      outline_photo_path: {
        file_path: "/category/2025-05-11-68206c1bbac65.svg",
        original_width: "800px",
        original_height: "800px",
      },
      png_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      fill_photo_path: {
        file_path: "/category/2025-05-11-68206c16d271f.svg",
        original_width: "800px",
        original_height: "800px",
      },
      banner_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      created_at: "2025-05-11T09:21:36.000000Z",
      updated_at: "2025-06-13T07:41:57.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      status: 1,
      position: 1,
    },
    {
      id: 21,
      category_id: 7,
      language_code: "tr",
      country_iso: null,
      name: "Tişörtü",
      similar_words:
        '["tisort","tişört","tshirt","tşort","tishort","tşirt","tisortler","tişörtler","tshirtler","tşortlar","tishortlar","tşirtlar","ti","t","shirt","shört","shırt","şort","tshırt","te","teşört","teşort","tişortu","tisortu","tşortu","tshirtu"]',
      slug: "tisortu-21",
      bio: "<p>Tiş&ouml;rt&uuml;</p>",
      description: "<p>Tiş&ouml;rt&uuml;</p>",
      flat_photo_path: {
        file_path: "/category/2025-05-11-68206c207aedc.svg",
        original_width: "800px",
        original_height: "800px",
      },
      outline_photo_path: {
        file_path: "/category/2025-05-11-68206c29896a3.svg",
        original_width: "800px",
        original_height: "800px",
      },
      png_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      fill_photo_path: {
        file_path: "/category/2025-05-11-68206c251beae.svg",
        original_width: "800px",
        original_height: "800px",
      },
      banner_photo_path: {
        file_path: null,
        original_width: "0",
        original_height: "0",
      },
      created_at: "2025-05-11T09:21:50.000000Z",
      updated_at: "2025-06-13T07:46:27.000000Z",
      added_by_type: 2,
      added_by_id: 80,
      deleted_by_type: null,
      deleted_by_id: null,
      deleted_at: null,
      status: 1,
      position: 1,
    },
  ],
  seller_status: null,
  start_date: null,
  end_date: null,
  flash_deal_status: null,
};
