import '../../globals.css'
import dynamic from 'next/dynamic'
const Providers = dynamic(() => import("../../../redux/provider"), {
ssr: false,
});
import GAComponent from "../../../components/global/GAComponent"

export const metadata = {
  title: 'TryDos',
  description: 'Generated by create next app',
}

export default function RootLayout({params:{lang} ,children }) {

  return (
    <html lang="en">
       <GAComponent/>

     <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K8QKJJLK"
height="0" width="0" style={{"display":"none",visibility:"hidden"}}></iframe></noscript>
        <Providers lang={lang}>
           {children}
        </Providers>
        </body>
    

    </html>
  )
}
