import './globals.css'
import {Providers} from "../redux/provider"
import Smartlook from 'smartlook-client'
import { SSRDetect, getUserChat } from '../utils/functions'
export const metadata = {
  title: 'TryDos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
     <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
        <Providers>
           {children}
        </Providers>
        </body>
    

    </html>
  )
}
