import './globals.css'
require( "external-svg-loader");
import { Inter } from 'next/font/google'
import {Providers} from "../redux/provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TryDos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
        <Providers>
           {children}
        </Providers>
        </body>
    

    </html>
  )
}
