import { Metadata } from "next";

export interface SEOConfig {
  title?: string;
  description?: string;
  keywords?: string[];
  image?: string;
  url?: string;
  type?: "website" | "article" | "product" | "profile";
  siteName?: string;
  locale?: string;
  alternates?: {
    canonical?: string;
    languages?: Record<string, string>;
  };
  robots?: {
    index?: boolean;
    follow?: boolean;
    googleBot?: {
      index?: boolean;
      follow?: boolean;
      "max-video-preview"?: number;
      "max-image-preview"?: "none" | "standard" | "large";
      "max-snippet"?: number;
    };
  };
  openGraph?: {
    type?: "website" | "article" | "product" | "profile";
    title?: string;
    description?: string;
    url?: string;
    siteName?: string;
    images?: Array<{
      url: string;
      width?: number;
      height?: number;
      alt?: string;
      type?: string;
    }>;
    locale?: string;
    alternateLocale?: string[];
  };
  twitter?: {
    card?: "summary" | "summary_large_image" | "app" | "player";
    site?: string;
    creator?: string;
    title?: string;
    description?: string;
    images?: string[];
  };
  verification?: {
    google?: string;
    yandex?: string;
    yahoo?: string;
    other?: Record<string, string>;
  };
}

const defaultSEOConfig: SEOConfig = {
  siteName: "TryDos",
  type: "website",
  locale: "en_US",
  keywords: [
    "online shopping",
    "premium products",
    "fashion",
    "boutique",
    "e-commerce",
    "shopping mall",
    "brands",
    "lifestyle",
    "accessories",
    "clothing",
    "electronics",
    "home decor",
    "beauty",
    "health",
    "sports",
    "automotive",
    "books",
    "toys",
    "gifts",
    "sale",
    "discount",
    "free shipping",
    "fast delivery",
    "secure payment",
    "customer service",
    "reviews",
    "quality products",
    "trending",
    "latest",
    "new arrivals",
    "best sellers",
    "exclusive deals",
    "flash sales",
    "seasonal offers",
    "mobile app",
    "user-friendly",
    "easy returns",
    "warranty",
    "authentic products",
    "customer satisfaction",
    "global shipping",
    "multiple payment options",
    "wishlist",
    "favorites",
    "compare products",
    "product reviews",
    "customer ratings",
    "social shopping",
    "personalized recommendations",
    "AI-powered search",
    "voice search",
    "image search",
    "augmented reality",
    "virtual try-on",
    "size guide",
    "fit finder",
    "style advisor",
    "outfit ideas",
    "lookbook",
    "seasonal collections",
    "limited edition",
    "pre-order",
    "back in stock",
    "price drop alerts",
    "inventory updates",
    "product availability",
    "shipping tracking",
    "order history",
    "repeat orders",
    "subscription service",
    "loyalty program",
    "reward points",
    "referral program",
    "gift cards",
    "gift wrapping",
    "occasion gifts",
    "holiday specials",
    "birthday gifts",
    "anniversary gifts",
    "wedding gifts",
    "corporate gifts",
    "bulk orders",
    "wholesale",
    "business accounts",
    "trade discounts",
    "volume pricing",
    "custom orders",
    "personalization",
    "monogramming",
    "engraving",
    "embroidery",
    "alterations",
    "tailoring",
    "styling services",
    "personal shopper",
    "concierge service",
    "VIP treatment",
    "exclusive access",
    "early bird offers",
    "member benefits",
    "special events",
    "product launches",
    "brand collaborations",
    "influencer partnerships",
    "social media integration",
    "user-generated content",
    "community features",
    "discussion forums",
    "Q&A sections",
    "expert advice",
    "buying guides",
    "how-to videos",
    "product demonstrations",
    "virtual consultations",
    "live chat support",
    "24/7 customer service",
    "multilingual support",
    "accessibility features",
    "mobile-first design",
    "responsive layout",
    "fast loading",
    "SEO optimized",
    "local SEO",
    "international SEO",
    "schema markup",
    "rich snippets",
    "product feed",
    "Google Shopping",
    "social commerce",
    "marketplace integration",
    "third-party sellers",
    "verified merchants",
    "seller ratings",
    "trusted brands",
    "authorized dealers",
    "official stores",
    "flagship stores",
    "pop-up shops",
    "seasonal stores",
    "clearance sales",
    "outlet prices",
    "factory direct",
    "wholesale prices",
    "member-only deals",
    "flash discounts",
    "time-limited offers",
    "quantity discounts",
    "bundle deals",
    "combo offers",
    "buy-one-get-one",
    "free gifts",
    "promotional codes",
    "coupon codes",
    "discount vouchers",
    "cashback offers",
    "loyalty rewards",
    "point redemption",
    "tier benefits",
    "status upgrades",
    "exclusive privileges",
    "priority access",
    "early previews",
    "beta testing",
    "feedback opportunities",
    "survey participation",
    "product testing",
    "brand ambassadors",
    "influencer programs",
    "affiliate marketing",
    "partnership opportunities",
    "dropshipping",
    "fulfillment services",
    "logistics support",
    "inventory management",
    "order processing",
    "payment processing",
    "fraud protection",
    "secure checkout",
    "SSL encryption",
    "data privacy",
    "GDPR compliance",
    "cookie policy",
    "terms of service",
    "privacy policy",
    "return policy",
    "shipping policy",
    "warranty terms",
    "user agreement",
    "community guidelines",
    "content policies",
    "intellectual property",
    "trademark protection",
    "copyright compliance",
    "brand guidelines",
    "quality standards",
    "safety regulations",
    "environmental responsibility",
    "sustainability initiatives",
    "eco-friendly products",
    "recycling programs",
    "carbon footprint",
    "green shipping",
    "sustainable packaging",
    "biodegradable materials",
    "renewable energy",
    "ethical sourcing",
    "fair trade",
    "social responsibility",
    "charitable giving",
    "community support",
    "local businesses",
    "small businesses",
    "entrepreneurship",
    "innovation",
    "technology",
    "digital transformation",
    "AI and machine learning",
    "data analytics",
    "predictive modeling",
    "personalization engines",
    "recommendation algorithms",
    "search optimization",
    "conversion optimization",
    "A/B testing",
    "user experience",
    "user interface",
    "design thinking",
    "customer journey",
    "touchpoint optimization",
    "omnichannel experience",
    "cross-platform consistency",
    "device compatibility",
    "browser support",
    "performance optimization",
    "speed optimization",
    "SEO best practices",
    "technical SEO",
    "on-page SEO",
    "off-page SEO",
    "link building",
    "content marketing",
    "social media marketing",
    "email marketing",
    "influencer marketing",
    "paid advertising",
    "search engine marketing",
    "display advertising",
    "retargeting campaigns",
    "conversion tracking",
    "analytics and reporting",
    "business intelligence",
    "market research",
    "competitive analysis",
    "industry trends",
    "consumer behavior",
    "market segmentation",
    "target audience",
    "buyer personas",
    "customer profiling",
    "demographic analysis",
    "psychographic insights",
    "behavioral targeting",
    "geographic targeting",
    "seasonal trends",
    "cultural preferences",
    "language localization",
    "currency conversion",
    "international shipping",
    "customs handling",
    "tax calculation",
    "duty fees",
    "import regulations",
    "export compliance",
    "trade agreements",
    "free trade zones",
    "duty-free shopping",
    "tax-free shopping",
    "VAT exemptions",
    "diplomatic sales",
    "tourist shopping",
    "travel retail",
    "airport shopping",
    "duty-free stores",
    "cruise shopping",
    "hotel shopping",
    "resort shopping",
    "vacation shopping",
    "leisure shopping",
    "entertainment shopping",
    "experience shopping",
    "immersive shopping",
    "virtual shopping",
    "augmented reality shopping",
    "mixed reality experiences",
    "virtual reality stores",
    "digital showrooms",
    "online galleries",
    "virtual exhibitions",
    "digital catalogs",
    "interactive lookbooks",
    "shoppable content",
    "social shopping",
    "live shopping",
    "video shopping",
    "livestream shopping",
    "influencer shopping",
    "celebrity endorsements",
    "brand partnerships",
    "collaborative collections",
    "limited editions",
    "exclusive releases",
    "collector items",
    "vintage products",
    "antique items",
    "rare finds",
    "unique pieces",
    "one-of-a-kind items",
    "handmade products",
    "artisan crafts",
    "local artisans",
    "traditional crafts",
    "cultural products",
    "heritage items",
    "authentic goods",
    "original designs",
    "custom creations",
    "bespoke services",
    "made-to-order",
    "personalized items",
    "customization options",
    "configuration tools",
    "design studios",
    "creation platforms",
    "maker spaces",
    "DIY kits",
    "craft supplies",
    "hobby materials",
    "educational resources",
    "skill development",
    "learning opportunities",
    "tutorial content",
    "expert guidance",
    "mentorship programs",
    "workshop sessions",
    "masterclasses",
    "certification courses",
    "professional development",
    "career advancement",
    "skill certification",
    "industry recognition",
    "achievement badges",
    "completion certificates",
    "continuing education",
    "lifelong learning",
    "knowledge sharing",
    "community learning",
    "peer-to-peer learning",
    "collaborative learning",
    "social learning",
    "gamified learning",
    "interactive learning",
    "adaptive learning",
    "personalized learning",
    "AI-powered learning",
    "machine learning applications",
    "predictive analytics",
    "behavioral insights",
    "customer intelligence",
    "market intelligence",
    "competitive intelligence",
    "business insights",
    "performance metrics",
    "key performance indicators",
    "success metrics",
    "ROI measurement",
    "conversion metrics",
    "engagement metrics",
    "satisfaction metrics",
    "loyalty metrics",
    "retention metrics",
    "acquisition metrics",
    "lifetime value",
    "customer acquisition cost",
    "return on ad spend",
    "cost per acquisition",
    "cost per click",
    "cost per impression",
    "click-through rate",
    "conversion rate",
    "bounce rate",
    "engagement rate",
    "dwell time",
    "session duration",
    "page views",
    "unique visitors",
    "returning visitors",
    "new visitors",
    "traffic sources",
    "referral traffic",
    "organic traffic",
    "paid traffic",
    "direct traffic",
    "social traffic",
    "email traffic",
    "search traffic",
    "mobile traffic",
    "desktop traffic",
    "tablet traffic",
    "cross-device tracking",
    "multi-touch attribution",
    "customer journey mapping",
    "funnel optimization",
    "conversion path analysis",
    "user flow analysis",
    "behavior flow",
    "heat mapping",
    "click tracking",
    "scroll tracking",
    "form analytics",
    "checkout analytics",
    "abandonment analysis",
    "exit intent detection",
    "real-time analytics",
    "predictive analytics",
    "forecasting models",
    "trend analysis",
    "pattern recognition",
    "anomaly detection",
    "fraud detection",
    "risk assessment",
    "security monitoring",
    "threat detection",
    "vulnerability assessment",
    "compliance monitoring",
    "audit trails",
    "access controls",
    "permission management",
    "user authentication",
    "multi-factor authentication",
    "single sign-on",
    "identity management",
    "account security",
    "password policies",
    "session management",
    "token management",
    "API security",
    "endpoint protection",
    "network security",
    "firewall protection",
    "intrusion detection",
    "malware protection",
    "virus scanning",
    "security updates",
    "patch management",
    "vulnerability patching",
    "security testing",
    "penetration testing",
    "security audits",
    "compliance audits",
    "regulatory compliance",
    "industry standards",
    "best practices",
    "security frameworks",
    "governance models",
    "risk management",
    "business continuity",
    "disaster recovery",
    "backup systems",
    "data recovery",
    "system restoration",
    "failover mechanisms",
    "redundancy systems",
    "high availability",
    "load balancing",
    "auto-scaling",
    "performance monitoring",
    "uptime monitoring",
    "health checks",
    "system diagnostics",
    "error tracking",
    "log analysis",
    "debugging tools",
    "troubleshooting guides",
    "support documentation",
    "knowledge base",
    "FAQ sections",
    "help center",
    "customer support",
    "technical support",
    "live chat",
    "phone support",
    "email support",
    "ticket system",
    "escalation procedures",
    "service level agreements",
    "response times",
    "resolution times",
    "customer satisfaction",
    "support quality",
    "training programs",
    "certification requirements",
    "skill assessments",
    "performance evaluations",
    "feedback mechanisms",
    "continuous improvement",
    "process optimization",
    "workflow automation",
    "task automation",
    "rule-based automation",
    "AI-powered automation",
    "machine learning automation",
    "intelligent automation",
    "robotic process automation",
    "business process automation",
    "workflow management",
    "project management",
    "task management",
    "time management",
    "resource management",
    "capacity planning",
    "demand forecasting",
    "supply chain optimization",
    "inventory optimization",
    "procurement optimization",
    "vendor management",
    "supplier relationships",
    "partnership management",
    "contract management",
    "negotiation strategies",
    "cost optimization",
    "budget management",
    "financial planning",
    "revenue optimization",
    "profit maximization",
    "margin improvement",
    "pricing strategies",
    "dynamic pricing",
    "competitive pricing",
    "value-based pricing",
    "cost-plus pricing",
    "penetration pricing",
    "skimming pricing",
    "bundle pricing",
    "tiered pricing",
    "subscription pricing",
    "freemium models",
    "pay-per-use models",
    "usage-based pricing",
    "performance-based pricing",
    "outcome-based pricing",
    "value sharing models",
    "revenue sharing models",
    "profit sharing models",
    "partnership models",
    "collaboration models",
    "ecosystem models",
    "platform models",
    "marketplace models",
    "network effects",
    "scalability models",
    "growth models",
    "expansion strategies",
    "market penetration",
    "market development",
    "product development",
    "diversification strategies",
    "innovation strategies",
    "technology strategies",
    "digital strategies",
    "transformation strategies",
    "change management",
    "organizational development",
    "cultural transformation",
    "leadership development",
    "team building",
    "collaboration tools",
    "communication platforms",
    "knowledge management",
    "information sharing",
    "best practice sharing",
    "lessons learned",
    "continuous learning",
    "adaptive capacity",
    "resilience building",
    "crisis management",
    "emergency response",
    "contingency planning",
    "scenario planning",
    "strategic planning",
    "tactical planning",
    "operational planning",
    "execution excellence",
    "performance excellence",
    "quality excellence",
    "customer excellence",
    "service excellence",
    "operational excellence",
    "organizational excellence",
    "leadership excellence",
    "innovation excellence",
    "technology excellence",
    "digital excellence",
    "data excellence",
    "analytics excellence",
    "insights excellence",
    "decision excellence",
    "strategic excellence",
    "competitive excellence",
    "market excellence",
    "brand excellence",
    "customer experience excellence",
    "employee experience excellence",
    "stakeholder experience excellence",
    "investor experience excellence",
    "partner experience excellence",
    "supplier experience excellence",
    "community experience excellence",
    "social impact excellence",
    "environmental impact excellence",
    "sustainability excellence",
    "governance excellence",
    "compliance excellence",
    "risk management excellence",
    "security excellence",
    "privacy excellence",
    "transparency excellence",
    "accountability excellence",
    "ethical excellence",
    "integrity excellence",
    "trust excellence",
    "reputation excellence",
    "brand reputation",
    "corporate reputation",
    "market reputation",
    "industry reputation",
    "thought leadership",
    "market leadership",
    "technology leadership",
    "innovation leadership",
    "digital leadership",
    "customer leadership",
    "service leadership",
    "quality leadership",
    "operational leadership",
    "organizational leadership",
    "cultural leadership",
    "social leadership",
    "environmental leadership",
    "sustainability leadership",
    "governance leadership",
    "ethical leadership",
    "transformational leadership",
    "visionary leadership",
    "strategic leadership",
    "adaptive leadership",
    "resilient leadership",
    "collaborative leadership",
    "inclusive leadership",
    "diverse leadership",
    "global leadership",
    "local leadership",
    "community leadership",
    "stakeholder leadership",
    "shareholder leadership",
    "customer-centric leadership",
    "employee-centric leadership",
    "people-centric leadership",
    "human-centric leadership",
    "purpose-driven leadership",
    "values-driven leadership",
    "mission-driven leadership",
    "vision-driven leadership",
    "impact-driven leadership",
    "results-driven leadership",
    "performance-driven leadership",
    "excellence-driven leadership",
    "innovation-driven leadership",
    "growth-driven leadership",
    "sustainability-driven leadership",
    "responsibility-driven leadership",
    "integrity-driven leadership",
    "trust-driven leadership",
    "transparency-driven leadership",
    "accountability-driven leadership",
    "collaborative-driven leadership",
    "inclusive-driven leadership",
    "diverse-driven leadership",
    "equitable-driven leadership",
    "fair-driven leadership",
    "ethical-driven leadership",
    "responsible-driven leadership",
    "sustainable-driven leadership",
    "long-term-driven leadership",
    "stakeholder-driven leadership",
    "customer-driven leadership",
    "employee-driven leadership",
    "community-driven leadership",
    "society-driven leadership",
    "planet-driven leadership",
    "future-driven leadership",
    "next-generation leadership",
    "emerging leadership",
    "developing leadership",
    "nurturing leadership",
    "mentoring leadership",
    "coaching leadership",
    "empowering leadership",
    "enabling leadership",
    "facilitating leadership",
    "supporting leadership",
    "encouraging leadership",
    "inspiring leadership",
    "motivating leadership",
    "engaging leadership",
    "connecting leadership",
    "communicating leadership",
    "listening leadership",
    "understanding leadership",
    "empathetic leadership",
    "compassionate leadership",
    "caring leadership",
    "serving leadership",
    "servant leadership",
    "stewardship leadership",
    "custodial leadership",
    "guardianship leadership",
    "protective leadership",
    "defensive leadership",
    "preventive leadership",
    "proactive leadership",
    "anticipatory leadership",
    "predictive leadership",
    "forward-thinking leadership",
    "strategic thinking",
    "critical thinking",
    "creative thinking",
    "innovative thinking",
    "design thinking",
    "systems thinking",
    "holistic thinking",
    "integrated thinking",
    "cross-functional thinking",
    "interdisciplinary thinking",
    "multidisciplinary thinking",
    "transdisciplinary thinking",
    "collaborative thinking",
    "collective thinking",
    "shared thinking",
    "distributed thinking",
    "networked thinking",
    "connected thinking",
    "global thinking",
    "local thinking",
    "contextual thinking",
    "situational thinking",
    "adaptive thinking",
    "flexible thinking",
    "agile thinking",
    "responsive thinking",
    "resilient thinking",
    "antifragile thinking",
    "growth thinking",
    "learning thinking",
    "curious thinking",
    "questioning thinking",
    "exploring thinking",
    "discovering thinking",
    "experimenting thinking",
    "testing thinking",
    "validating thinking",
    "iterating thinking",
    "refining thinking",
    "improving thinking",
    "optimizing thinking",
    "enhancing thinking",
    "upgrading thinking",
    "evolving thinking",
    "transforming thinking",
    "revolutionizing thinking",
    "disrupting thinking",
    "challenging thinking",
    "rethinking thinking",
    "reimagining thinking",
    "reinventing thinking",
    "recreating thinking",
    "rebuilding thinking",
    "reconstructing thinking",
    "restructuring thinking",
    "reforming thinking",
    "renewing thinking",
    "refreshing thinking",
    "revitalizing thinking",
    "rejuvenating thinking",
    "regenerating thinking",
    "restoring thinking",
    "rehabilitating thinking",
    "recovering thinking",
    "healing thinking",
    "therapeutic thinking",
    "remedial thinking",
    "corrective thinking",
    "preventive thinking",
    "protective thinking",
    "defensive thinking",
    "security thinking",
    "safety thinking",
    "risk thinking",
    "uncertainty thinking",
    "ambiguity thinking",
    "complexity thinking",
    "chaos thinking",
    "order thinking",
    "structure thinking",
    "organization thinking",
    "management thinking",
    "leadership thinking",
    "governance thinking",
    "stewardship thinking",
    "custodianship thinking",
    "ownership thinking",
    "responsibility thinking",
    "accountability thinking",
    "transparency thinking",
    "openness thinking",
    "honesty thinking",
    "integrity thinking",
    "ethics thinking",
    "morality thinking",
    "values thinking",
    "principles thinking",
    "standards thinking",
    "benchmarks thinking",
    "best practices thinking",
    "excellence thinking",
    "quality thinking",
    "perfection thinking",
    "mastery thinking",
    "expertise thinking",
    "proficiency thinking",
    "competence thinking",
    "capability thinking",
    "capacity thinking",
    "potential thinking",
    "possibility thinking",
    "opportunity thinking",
    "advantage thinking",
    "benefit thinking",
    "value thinking",
    "worth thinking",
    "merit thinking",
    "significance thinking",
    "importance thinking",
    "relevance thinking",
    "meaning thinking",
    "purpose thinking",
    "mission thinking",
    "vision thinking",
    "goal thinking",
    "objective thinking",
    "target thinking",
    "aim thinking",
    "intention thinking",
    "plan thinking",
    "strategy thinking",
    "tactics thinking",
    "approach thinking",
    "method thinking",
    "technique thinking",
    "process thinking",
    "procedure thinking",
    "system thinking",
    "framework thinking",
    "model thinking",
    "paradigm thinking",
    "perspective thinking",
    "viewpoint thinking",
    "standpoint thinking",
    "position thinking",
    "stance thinking",
    "attitude thinking",
    "mindset thinking",
    "mentality thinking",
    "psychology thinking",
    "behavior thinking",
    "action thinking",
    "reaction thinking",
    "response thinking",
    "interaction thinking",
    "engagement thinking",
    "involvement thinking",
    "participation thinking",
    "collaboration thinking",
    "cooperation thinking",
    "coordination thinking",
    "integration thinking",
    "alignment thinking",
    "synchronization thinking",
    "harmonization thinking",
    "balance thinking",
    "equilibrium thinking",
    "stability thinking",
    "consistency thinking",
    "reliability thinking",
    "dependability thinking",
    "trustworthiness thinking",
    "credibility thinking",
    "authenticity thinking",
    "genuineness thinking",
    "sincerity thinking",
    "honesty thinking",
    "truthfulness thinking",
    "accuracy thinking",
    "precision thinking",
    "exactness thinking",
    "correctness thinking",
    "validity thinking",
    "reliability thinking",
    "consistency thinking",
    "stability thinking",
    "predictability thinking",
    "certainty thinking",
    "confidence thinking",
    "assurance thinking",
    "security thinking",
    "safety thinking",
    "protection thinking",
    "defense thinking",
    "prevention thinking",
    "precaution thinking",
    "preparation thinking",
    "readiness thinking",
    "alertness thinking",
    "vigilance thinking",
    "awareness thinking",
    "consciousness thinking",
    "mindfulness thinking",
    "attention thinking",
    "focus thinking",
    "concentration thinking",
    "dedication thinking",
    "commitment thinking",
    "devotion thinking",
    "loyalty thinking",
    "faithfulness thinking",
    "fidelity thinking",
    "steadfastness thinking",
    "perseverance thinking",
    "persistence thinking",
    "determination thinking",
    "resolution thinking",
    "resolve thinking",
    "willpower thinking",
    "strength thinking",
    "power thinking",
    "force thinking",
    "energy thinking",
    "vitality thinking",
    "vigor thinking",
    "dynamism thinking",
    "enthusiasm thinking",
    "passion thinking",
    "excitement thinking",
    "inspiration thinking",
    "motivation thinking",
    "drive thinking",
    "ambition thinking",
    "aspiration thinking",
    "desire thinking",
    "wish thinking",
    "hope thinking",
    "expectation thinking",
    "anticipation thinking",
    "prediction thinking",
    "forecast thinking",
    "projection thinking",
    "estimation thinking",
    "calculation thinking",
    "computation thinking",
    "analysis thinking",
    "evaluation thinking",
    "assessment thinking",
    "judgment thinking",
    "decision thinking",
    "choice thinking",
    "selection thinking",
    "option thinking",
    "alternative thinking",
    "possibility thinking",
    "opportunity thinking",
    "chance thinking",
    "probability thinking",
    "likelihood thinking",
    "potential thinking",
    "capability thinking",
    "capacity thinking",
    "ability thinking",
    "skill thinking",
    "talent thinking",
    "gift thinking",
    "expertise thinking",
    "knowledge thinking",
    "wisdom thinking",
    "intelligence thinking",
    "understanding thinking",
    "comprehension thinking",
    "insight thinking",
    "awareness thinking",
    "consciousness thinking",
    "recognition thinking",
    "realization thinking",
    "acknowledgment thinking",
    "acceptance thinking",
    "approval thinking",
    "agreement thinking",
    "consensus thinking",
    "harmony thinking",
    "unity thinking",
    "solidarity thinking",
    "togetherness thinking",
    "partnership thinking",
    "alliance thinking",
    "coalition thinking",
    "collaboration thinking",
    "cooperation thinking",
    "teamwork thinking",
    "synergy thinking",
    "coordination thinking",
    "integration thinking",
    "combination thinking",
    "merger thinking",
    "fusion thinking",
    "synthesis thinking",
    "unification thinking",
    "consolidation thinking",
    "centralization thinking",
    "standardization thinking",
    "normalization thinking",
    "regularization thinking",
    "systematization thinking",
    "organization thinking",
    "structure thinking",
    "order thinking",
    "arrangement thinking",
    "configuration thinking",
    "setup thinking",
    "establishment thinking",
    "creation thinking",
    "formation thinking",
    "development thinking",
    "construction thinking",
    "building thinking",
    "assembly thinking",
    "production thinking",
    "manufacturing thinking",
    "making thinking",
    "crafting thinking",
    "designing thinking",
    "styling thinking",
    "fashioning thinking",
    "shaping thinking",
    "molding thinking",
    "forming thinking",
    "structuring thinking",
    "organizing thinking",
    "systematizing thinking",
    "methodizing thinking",
    "regularizing thinking",
    "standardizing thinking",
    "normalizing thinking",
    "optimizing thinking",
    "improving thinking",
    "enhancing thinking",
    "upgrading thinking",
    "advancement thinking",
    "progressing thinking",
    "developing thinking",
    "evolving thinking",
    "transforming thinking",
    "changing thinking",
    "adapting thinking",
    "adjusting thinking",
    "modifying thinking",
    "altering thinking",
    "revising thinking",
    "updating thinking",
    "renewing thinking",
    "refreshing thinking",
    "revitalizing thinking",
    "regenerating thinking",
    "restoring thinking",
    "rehabilitating thinking",
    "recovering thinking",
    "healing thinking",
    "repairing thinking",
    "fixing thinking",
    "correcting thinking",
    "rectifying thinking",
    "remedying thinking",
    "solving thinking",
    "resolving thinking",
    "answering thinking",
    "responding thinking",
    "reacting thinking",
    "feedback thinking",
    "input thinking",
    "contribution thinking",
    "participation thinking",
    "involvement thinking",
    "engagement thinking",
    "interaction thinking",
    "communication thinking",
    "dialogue thinking",
    "conversation thinking",
    "discussion thinking",
    "debate thinking",
    "argument thinking",
    "reasoning thinking",
    "logic thinking",
    "rationality thinking",
    "objectivity thinking",
    "neutrality thinking",
    "impartiality thinking",
    "fairness thinking",
    "justice thinking",
    "equity thinking",
    "equality thinking",
    "balance thinking",
    "harmony thinking",
    "peace thinking",
    "tranquility thinking",
    "serenity thinking",
    "calm thinking",
    "quiet thinking",
    "silence thinking",
    "stillness thinking",
    "rest thinking",
    "relaxation thinking",
    "comfort thinking",
    "ease thinking",
    "convenience thinking",
    "simplicity thinking",
    "clarity thinking",
    "transparency thinking",
    "openness thinking",
    "honesty thinking",
    "truthfulness thinking",
    "sincerity thinking",
    "genuineness thinking",
    "authenticity thinking",
    "originality thinking",
    "uniqueness thinking",
    "distinctiveness thinking",
    "individuality thinking",
    "personality thinking",
    "character thinking",
    "identity thinking",
  ],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    siteName: "TryDos",
    locale: "en_US",
    alternateLocale: ["ar_SA", "tr_TR"],
  },
  twitter: {
    card: "summary_large_image",
    site: "@trydos",
    creator: "@trydos",
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    // Add other verification codes as needed
  },
};

export function generateMetadata(config: SEOConfig = {}): Metadata {
  const mergedConfig = { ...defaultSEOConfig, ...config };
  const baseUrl = process.env.NEXT_PUBLIC_REMOTE_FRONT || "https://trydos.com";

  const metadata: Metadata = {
    title: mergedConfig.title || "TryDos - Premium Shopping Experience",
    description:
      mergedConfig.description ||
      "Discover premium products and exceptional shopping experience with TryDos. Shop from top brands and boutiques with fast delivery and secure payment.",
    keywords: mergedConfig.keywords,
    metadataBase: new URL(baseUrl),
    alternates: {
      canonical: mergedConfig.alternates?.canonical || mergedConfig.url,
      languages: mergedConfig.alternates?.languages || {
        "en-US": "/en-us",
        "ar-SA": "/ar-sa",
        "tr-TR": "/tr-tr",
        "x-default": "/en-us",
      },
    },
    robots: mergedConfig.robots,
    openGraph: {
      type:
        (mergedConfig.openGraph?.type === "product"
          ? "website"
          : mergedConfig.openGraph?.type) || "website",
      title: mergedConfig.openGraph?.title || mergedConfig.title,
      description:
        mergedConfig.openGraph?.description || mergedConfig.description,
      url: mergedConfig.openGraph?.url || mergedConfig.url,
      siteName: mergedConfig.openGraph?.siteName || "TryDos",
      locale: mergedConfig.openGraph?.locale || "en_US",
      alternateLocale: mergedConfig.openGraph?.alternateLocale || [
        "ar_SA",
        "tr_TR",
      ],
      images: mergedConfig.openGraph?.images || [
        {
          url: mergedConfig.image || `${baseUrl}/opengraph-image.png`,
          width: 1200,
          height: 630,
          alt: mergedConfig.title || "TryDos - Premium Shopping Experience",
          type: "image/png",
        },
      ],
    },
    twitter: {
      card: mergedConfig.twitter?.card || "summary_large_image",
      site: mergedConfig.twitter?.site || "@trydos",
      creator: mergedConfig.twitter?.creator || "@trydos",
      title: mergedConfig.twitter?.title || mergedConfig.title,
      description:
        mergedConfig.twitter?.description || mergedConfig.description,
      images: mergedConfig.twitter?.images || [
        mergedConfig.image || `${baseUrl}/opengraph-image.png`,
      ],
    },
    verification: mergedConfig.verification,
    category: "e-commerce",
    classification: "shopping",
    referrer: "origin-when-cross-origin",
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
    manifest: `${baseUrl}/manifest.json`,
    appleWebApp: {
      capable: true,
      title: mergedConfig.title || "TryDos",
      statusBarStyle: "default",
      startupImage: [
        {
          url: `${baseUrl}/apple-touch-startup-image.png`,
          media:
            "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)",
        },
      ],
    },
    applicationName: "TryDos",
    generator: "Next.js",
    publisher: "TryDos",
    creator: "TryDos Team",
    authors: [{ name: "TryDos Team", url: baseUrl }],
    bookmarks: [`${baseUrl}/bookmarks`],
    archives: [`${baseUrl}/archives`],
    assets: [`${baseUrl}/assets`],
    other: {
      "mobile-web-app-capable": "yes",
      "apple-mobile-web-app-capable": "yes",
      "apple-mobile-web-app-status-bar-style": "default",
      "apple-mobile-web-app-title": mergedConfig.title || "TryDos",
      "application-name": "TryDos",
      "msapplication-TileColor": "#ffffff",
      "msapplication-config": `${baseUrl}/browserconfig.xml`,
      "theme-color": "#ffffff",
      "color-scheme": "light dark",
      "supported-color-schemes": "light dark",
    },
  };

  return metadata;
}

// Common metadata generators for different page types
export const generateHomeMetadata = (
  customConfig: SEOConfig = {}
): Metadata => {
  return generateMetadata({
    title: "TryDos - Premium Shopping Experience | Online Mall",
    description:
      "Discover premium products and exceptional shopping experience with TryDos. Shop from top brands and boutiques with fast delivery, secure payment, and 24/7 support.",
    type: "website",
    ...customConfig,
  });
};

export const generateProductMetadata = (
  product: {
    title: string;
    description: string;
    price?: number;
    currency?: string;
    image?: string;
    category?: string;
    brand?: string;
    availability?: string;
    condition?: string;
    url?: string;
  },
  customConfig: SEOConfig = {}
): Metadata => {
  const baseUrl = process.env.NEXT_PUBLIC_REMOTE_FRONT || "https://trydos.com";

  return generateMetadata({
    title: `${product.title} - TryDos`,
    description: product.description,
    type: "product",
    image: product.image,
    url: product.url,
    keywords: [
      product.title,
      product.brand,
      product.category,
      "online shopping",
      "premium products",
      "buy online",
      "fast delivery",
      "secure payment",
      ...(customConfig.keywords || []),
    ].filter(Boolean),
    openGraph: {
      type: "website",
      title: product.title,
      description: product.description,
      images: [
        {
          url: product.image || `${baseUrl}/opengraph-image.png`,
          width: 1200,
          height: 630,
          alt: product.title,
        },
      ],
      ...customConfig.openGraph,
    },
    ...customConfig,
  });
};

export const generateCategoryMetadata = (
  category: {
    name: string;
    description: string;
    image?: string;
    url?: string;
  },
  customConfig: SEOConfig = {}
): Metadata => {
  return generateMetadata({
    title: `${category.name} - Shop Premium Products | TryDos`,
    description: category.description,
    type: "website",
    image: category.image,
    url: category.url,
    keywords: [
      category.name,
      "online shopping",
      "premium products",
      "brands",
      "boutiques",
      "fast delivery",
      "secure payment",
      ...(customConfig.keywords || []),
    ].filter(Boolean),
    ...customConfig,
  });
};

export const generateBrandMetadata = (
  brand: {
    name: string;
    description: string;
    image?: string;
    url?: string;
  },
  customConfig: SEOConfig = {}
): Metadata => {
  return generateMetadata({
    title: `${brand.name} - Official Brand Store | TryDos`,
    description: brand.description,
    type: "website",
    image: brand.image,
    url: brand.url,
    keywords: [
      brand.name,
      "official store",
      "authentic products",
      "brand store",
      "premium quality",
      "fast delivery",
      "secure payment",
      ...(customConfig.keywords || []),
    ].filter(Boolean),
    ...customConfig,
  });
};
