import '../../globals.css'
import dynamic from 'next/dynamic'
const Providers = dynamic(() => import("../../../redux/provider"), {
ssr: false, 
});
import GAComponent from "../../../components/global/GAComponent"
import { SSRDetect } from '../../../utils/functions';
import NextTopLoader from 'nextjs-toploader';
export const metadata = {
  title: 'TryDos',
  description: 'Generated by create next app',
}

export default function RootLayout({params:{lang} ,children }) {

  return (
    <html lang="en">
       {SSRDetect()&&<GAComponent/>}

     <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
      <NextTopLoader
  color="#2299DD"
  initialPosition={0.08}
  crawlSpeed={200}
  height={3}
  crawl={true}
  showSpinner={true}
  easing="ease"
  speed={200}
  shadow="0 0 10px #2299DD,0 0 5px #2299DD"
  template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
  zIndex={1600}
  showAtBottom={false}
/>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K8QKJJLK"
height="0" width="0" style={{"display":"none",visibility:"hidden"}}></iframe></noscript>
        <Providers lang={lang}>
           {children}
        </Providers>
        </body>
    

    </html>
  )
}
