import "styles/globals.css";
import dynamic from "next/dynamic";
const Providers = dynamic(() => import("store/provider"), {
  ssr: false,
});
const NextTopLoader = dynamic(() => import("nextjs-toploader"), {
  ssr: false,
});
export const metadata = {
  title: "TryDos",
  description: "Generated by create next app",
};
// const sf_pro_rounded_bold = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Bold.ttf",
//   variable: "--SF-Pro-Rounded-Bold",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_light = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Light.ttf",
//   variable: "--SF-Pro-Rounded-Light",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_semibold = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Semibold.ttf",
//   variable: "--SF-Pro-Rounded-semibold",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_regular = localFont({
//   src: "../../../public/fonts/SF-Pro-Rounded.ttf",
//   variable: "--SF-Pro-Rounded-Regular",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_medium = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Medium.ttf",
//   variable: "--SF-Pro-Rounded-Medium",
//   display: "swap",
//   preload: false,
// });
// const icon_font = localFont({
//   src: "../../../public/fonts/NotoColorEmoji-Regular.ttf",
//   variable: "--icon-font",
//   display: "swap",
// });
// const quicksand_regular = localFont({
//   src: "../../../public/fonts/Quicksand-Regular.woff2",
//   variable: "--Quicksand-Regular",
//   display: "swap",
//   preload: false,
// });
// const quicksand_light = localFont({
//   src: "../../../public/fonts/Quicksand-Light.woff2",
//   variable: "--Quicksand-Light",
//   display: "swap",
//   preload: false,
// });
// const quicksand_bold = localFont({
//   src: "../../../public/fonts/Quicksand-Bold.woff2",
//   variable: "--Quicksand-Bold",
//   display: "swap",
//   preload: false,
// });
// const quicksand_medium = localFont({
//   src: "../../../public/fonts/Quicksand-Medium.woff2",
//   variable: "--Quicksand-Medium",
//   display: "swap",
//   preload: false,
// });
export default function RootLayout({ params: { lang }, children }) {
  // ${sf_pro_rounded_light.variable}
  // ${sf_pro_rounded_semibold.variable}
  // ${sf_pro_rounded_regular.variable}
  // ${sf_pro_rounded_medium.variable}
  // ${sf_pro_rounded_bold.variable}
  // ${quicksand_regular.variable}
  // ${quicksand_light.variable}
  // ${quicksand_medium.variable}
  // ${quicksand_bold.variable}
  return (
    <html
      className={`

      font-sans`}
      lang={lang.split("-")[1]}
    >
      <head>
        <style>
          {`.offers-list {
    align-items: flex-start;
    justify-content: flex-start;
    margin-top: 25px
}
.offer-widget,.offers-list {
    width: 100%;
    display: flex;
    flex-direction: column
}
.offer-widget {
    height: 54vw;
    max-height: 476px;
    min-height: 235px;
    position: relative;
    background-position: 50%;
    background-repeat: no-repeat;
    background-size: 169% 56vw;
    box-shadow: 0 3px 10px rgba(0,0,0,.1);
    border-radius: 15px;
    margin-top: 20px
}

.offer-widget:first-child {
    margin-top: 0
}

.offer-blured-background {
    background-color: hsla(0,0%,98%,.29)
}

.offer-blured,.offer-blured-background {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    border-radius: 15px;
    z-index: 1
}

.offer-blured {
    -webkit-backdrop-filter: blur(19px) brightness(239%);
    backdrop-filter: blur(19px) brightness(239%)
}
.offer-container {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: flex-start;
    overflow: hidden!important;
    justify-content: flex-start;
    z-index: 20;
    padding-top: 15px;
    flex-direction: column
}

.offer-logo {
    justify-content: center;
    margin-left: 25px
}

.offer-category,.offer-logo {
    display: flex;
    align-items: center
}

.offer-category {
    position: absolute;
    right: 15px;
    top: 15px
}

.offer-category svg {
    margin-right: 4px;
    transform: scale(.6)
}

.offer-category svg:last-child {
    margin-left: 0
}

.offer-desc {
    display: flex;
    align-items: center;
    font-family: var(--Quicksand-Regular);
    color: #505050;
    font-size: 12px;
    margin-left: 25px;
    margin-top: 4px
}

.offer-slider-container {
    margin-top: 9px;
    justify-content: center;
    margin-left: 3px;
    height: 31.4vw;
    width: 100%
}

.offer-slide-item,.offer-slider-container {
    display: flex;
    align-items: center;
    max-height: 342px
}

.offer-slide-item {
    justify-content: flex-start;
    position: relative;
    width: 95%;
    height: 100%
}

.offer-slide-item img {
    width: 100%;
    height: 100%;
    border-radius: 15px;
    -o-object-fit: cover;
    object-fit: cover;
    -o-object-position: center;
    object-position: center
}

.offer-avatars-container {
    display: flex;
    z-index: 9999;
    align-items: flex-end;
    position: absolute;
    left: 0;
    right: 0;
    margin-left: auto;
    margin-right: auto;
    bottom: 10%;
    width: -moz-fit-content;
    width: fit-content
}

.offer-avatar {
    cursor: pointer;
    transition: .3s;
    position: relative;
    display: flex;
    transform: translateX(-5px);
    filter: drop-shadow(0 3px 3px rgba(0,0,0,.16))
}

.offer-avatar,.offer-avatr-inner-s {
    width: 40px;
    height: 40px;
    border-radius: 50%
}

.offer-avatr-inner-s,.offer-more-s {
    box-shadow: inset 0 4px 6px hsla(0,0%,100%,.5);
    position: absolute;
    top: 0;
    left: 0;
    z-index: 15
}

.offer-more-s {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    background-color: rgba(0,0,0,.6)
}

.offer-avatar div {
    width: 100%;
    height: 100%
}

.offer-avatar-info {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
    height: 24px!important;
    opacity: 0;
    transition: .3s;
    top: 39px;
    padding-top: 4px;
    position: absolute;
    left: 0;
    font-family: var(--Quicksand-Regular);
    right: 0;
    margin-left: auto;
    margin-right: auto
}

.offer-avatar-info span:first-child {
    color: #929191;
    font-size: 12px;
    height: auto!important
}

.offer-avatar-info span:not(:first-child) {
    color: #b8b8b8;
    font-size: 10px;
    height: auto!important
}

.offer-avatar>span {
    font-family: var(--Quicksand-Regular);
    width: 100%;
    height: 100%;
    font-size: 10px;
    color: #fff;
    position: absolute;
    margin: 0 auto;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 20
}

.offer-avatar img {
    -o-object-position: center top;
    object-position: center top;
    -o-object-fit: cover;
    object-fit: cover;
    width: 100%;
    height: 100%!important
}
.logo-container {
    display: flex;
    min-width: 136px;
    align-items: flex-start
}

.categories-bar-container {
    display: flex;
    justify-content: flex-start;
    align-items: flex-start;
    padding-top: 7px;
    z-index: 90;
    max-width: 42%;
    margin-left: 50px
}

.categories-bar-container a,.categories-bar-item {
    display: flex;
    flex-direction: column;
    cursor: pointer;
    position: relative;
    max-width: 100%;
    justify-content: flex-start;
    align-items: flex-start
}

.categories-bar-container a:not(:first-child),.categories-bar-item:not(:first-child) {
    margin-left: 30px
}

.categories-bar-item-description {
    display: flex;
    bottom: -41.5px;
    right: -8px;
    position: absolute;
    opacity: 0;
    height: 40px;
    transition: .3s;
    flex-direction: row;
    align-items: flex-end;
    justify-content: flex-start
}

.categories-bar-item-icon {
    display: flex;
    transition: .3s;
    width: 100%
}
.search-component-container input {
    outline: none;
    border: none;
    flex: 1;
    font-size: 14px;
    color: #505050;
    margin-left: 10px;
    background-color: transparent
}
.categories-bar-item-name {
    display: flex;
    align-items: center;
    color: #505050;
    font-size: 12px
}

.categories-bar-item-name~svg {
    margin-left: 6px
}

.search-component-container {
    width: 58vw;
    flex: 1;
    display: flex;
    top: 26px;
    z-index: 10;
    background-color: #f5f5f5;
    border-radius: 10px;
    padding: 15px 20px;
    height: 50px;
    transition: .3s;
    max-width: 100%
}

.hide-bar {
    max-width: 0;
    left: 800px;
    height: 0;
    z-index: -1;
    position: absolute
}
.user-nav-container {
    display: flex;
    padding-top: 3px;
    align-items: center;
    justify-content: flex-end;
    flex: 1
}

.welcome-user {
    display: flex;
    color: #707070;
    font-size: 14px
}

.nav-question-item {
    display: flex;
    margin-left: 9px;
    align-items: center;
    cursor: pointer
}

.user-nav-container {
    position: relative
}
.translations-container-inner {
    display: flex;
    width: 60px;
    height: 60px;
    position: relative
}

.translation-icon {
    position: absolute;
    z-index: 10;
    top: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    left: 0;
    width: 60px;
    height: 60px;
    background-color: #f5f5f5;
    border-radius: 50%;
    box-shadow: 0 3px 10px rgba(0,0,0,.258)
}

.en-icon,.translation-icon {
    transition: all .3s ease-in-out
}

.en-icon {
    z-index: 8
}

.ar-icon {
    transition: all .5s ease-in-out;
    z-index: 7
}

.tr-icon {
    transition: all .7s ease-in-out;
    z-index: 6
}
.translations-container {
    display: flex;
    width: 60px;
    height: 50px;
    align-items: flex-end;
    position: fixed;
    z-index: 199;
    right: 20px;
    bottom: 30px
}
#Path_21306 {
    stroke-dashoffset: 21.4;
    stroke-dasharray: 21.4
}

.stories-bar {
    width: 100%;
    height: 200px;
    align-items: center;
    display: flex;
    justify-content: flex-start;
    position: relative;
    margin-top: 5px
}

.stories-bar::-webkit-scrollbar,.stories-bars::-webkit-scrollbar {
    width: 0;
    height: 0
}

.stories-bars {
    cursor: pointer;
    padding-right: 5px;
    overflow-x: scroll;
    overflow-y: hidden;
    white-space: nowrap;
    width: 100%;
    height: 200px;
    align-items: center;
    display: flex;
    justify-content: flex-start;
    padding-left: 15px
}
#stories-border1 {
    position: absolute;
    left: 0;
    top: 0
}

#stories-border2 {
    position: absolute;
    left: 0;
    bottom: 0
}

.stories-bar-container {
    transform: translateX(0);
    display: flex;
    width: 100vw;
    height: 200px;
    z-index: 99999999;
    max-width: 1365px;
    align-items: center;
    justify-content: flex-start;
    top: 95px;
    left: 0
}

.story-element-container {
    display: flex;
    min-width: 110px;
    max-width: 110px;
    height: 160px;
    position: relative;
    justify-content: flex-start;
    align-items: flex-end
}

.story-avatar {
    display: flex;
    position: absolute;
    top: 0;
    left: 0;
    width: 30px;
    height: 30px;
    background-color: #ffab62;
    z-index: 10
}

.story-avatar,.story-avatar img {
    align-items: center;
    justify-content: center;
    border-radius: 50%
}

.story-avatar img {
    width: 28px;
    height: 28px;
    -o-object-fit: cover;
    object-fit: cover;
    -o-object-position: center top;
    object-position: center top
}

.story-element-item {
    position: relative
}

.story-element-item,.story-element-item img {
    width: 100px;
    height: 150px;
    border-radius: 20px;
    display: flex
}

.story-element-item img {
    z-index: 2;
    -o-object-fit: cover;
    object-fit: cover
}

.linear-g-image {
    width: 100px;
    height: 150px;
    border-radius: 20px;
    background: linear-gradient(180deg,#00000000 0,#000 181%);
    z-index: 5;
    position: absolute;
    top: 0;
    left: 0
}

.story-element-container:not(:first-child) {
    margin-left: 5px
}

.story-text {
    align-items: center;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    width: 81px;
    display: block;
    right: 0;
    margin: 0 auto;
    position: absolute;
    bottom: 2px;
    left: 0;
    text-align: center;
    justify-content: center;
    font-size: 12px;
    font-family: var(--SF-Pro-Rounded-Regular);
    color: #fff;
    z-index: 12;
    letter-spacing: .003
}

.home-bar {
    width: 100%;
    height: 50px;
    max-width: 1366px;
    align-items: center;
    display: flex;
    border-radius: 15px;
    padding-left: 10px;
    cursor: pointer;
    background-color: #fafafa;
    box-shadow: 0 3px 10px rgba(0,0,0,.103);
    margin-top: 30px
}

.bar-desc-column {
    margin-left: 5px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: flex-start
}

.bar-name {
    display: flex;
    font-size: 14px;
    font-family: var(--Quicksand-Medium);
    color: #3c3c3c
}

.bar-desc {
    display: flex;
    font-size: 10px;
    font-family: var(--Quicksand-Regular);
    color: #505050
}
.image-border {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 1
}

img {
    max-width: 100%
}

body,html {
    margin: 0;
    padding: 0;
    height: 100%;
    overflow-x: hidden!important
}

.slick-slider,body,html {
    width: 100%
}

.image-offer {
    width: 100%;
    height: 100%;
    position: relative
}

.extended-widget {
    height: 67vw!important;
    background-size: 169% 67vw;
    max-height: 476px
}

.image-inner-shadow {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 10;
    box-shadow: inset 0 3px 6px hsla(0,0%,100%,.5);
    border-radius: 15px
}
.home-page-container {
    max-width: 1366px;
    flex-direction: column;
    padding: 30px
}

.home-navbar,.home-page-container {
    display: flex;
    width: 100%;
    justify-content: flex-start;
    align-items: center
}

.home-navbar {
    height: 84px;
    flex-direction: row
}`}
        </style>
      </head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
          zIndex={1600}
          showAtBottom={false}
        />
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K8QKJJLK"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}
