import "styles/globals.css";
import NextTopLoader from "nextjs-toploader";
import { ReactQueryClientProvider } from "components/Providers/ReactQueryClientProvider";
import Providers from "store/provider";
import localFont from "next/font/local";
export const metadata = {
  title: "TryDos",
  description: "Generated by create next app",
};
import type { Viewport } from "next";
import { getHomeData } from "store/homepage/cachedActions";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,
};
const aa = process.env.ENABLE_SENTRY;
// const sf_pro_rounded_bold = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Bold.ttf",
//   variable: "--SF-Pro-Rounded-Bold",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_light = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Light.ttf",
//   variable: "--SF-Pro-Rounded-Light",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_semibold = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Semibold.ttf",
//   variable: "--SF-Pro-Rounded-semibold",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_regular = localFont({
//   src: "../../../public/fonts/SF-Pro-Rounded.ttf",
//   variable: "--SF-Pro-Rounded-Regular",
//   display: "swap",
//   preload: false,
// });
// const sf_pro_rounded_medium = localFont({
//   src: "../../../public/fonts/FontsFree-Net-SF-Pro-Rounded-Medium.ttf",
//   variable: "--SF-Pro-Rounded-Medium",
//   display: "swap",
//   preload: false,
// });
// const icon_font = localFont({
//   src: "../../../public/fonts/NotoColorEmoji-Regular.ttf",
//   variable: "--icon-font",
//   display: "swap",
// });
const quicksand_regular = localFont({
  src: "../../../public/fonts/Quicksand-Regular.woff2",
  variable: "--Quicksand-Regular",
  display: "swap",
  preload: false,
});
const quicksand_light = localFont({
  src: "../../../public/fonts/Quicksand-Light.woff2",
  variable: "--Quicksand-Light",
  display: "swap",
  preload: false,
});
const quicksand_bold = localFont({
  src: "../../../public/fonts/Quicksand-Bold.woff2",
  variable: "--Quicksand-Bold",
  display: "swap",
  preload: false,
});
const quicksand_medium = localFont({
  src: "../../../public/fonts/Quicksand-Medium.woff2",
  variable: "--Quicksand-Medium",
  display: "swap",
  preload: false,
});
export default async function RootLayout({ params: { lang }, children }) {
  // ${sf_pro_rounded_light.variable}
  // ${sf_pro_rounded_semibold.variable}
  // ${sf_pro_rounded_regular.variable}
  // ${sf_pro_rounded_medium.variable}
  // ${sf_pro_rounded_bold.variable}
  const [HomeData, HomeData_res] = await getHomeData();
  return (
    <html
      className={`
      ${quicksand_regular.variable}
      ${quicksand_light.variable}
      ${quicksand_medium.variable}
      ${quicksand_bold.variable}
      font-sans`}
      lang={lang.split("-")[1]}
    >
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {HomeData[0] && (
          <link
            rel="preload"
            fetchPriority="high"
            href={HomeData[0]?.banners[0]}
            as="image"
          />
        )}
      </head>

      <body>
        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
          zIndex={1600}
          showAtBottom={false}
        />
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K8QKJJLK"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <ReactQueryClientProvider>
          <Providers lang={lang}>{children}</Providers>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
