export const REQUESTS_DATA = {
  GET_PRODUCT_VRIANTES: { reqTitle: "Get Product Vriantes", code: 10 },
  GET_PRODUCT_VARIANTS_NOTIFICATIONS: {
    reqTitle: "GEt Product Variants Notifications",
    code: 11,
  },
  SHARE_COUNT_REQUEST: { reqTitle: "Share Count Request", code: 12 },
  GET_PRODUCT_GLOBAL_DETAILS: {
    reqTitle: "GEt Product Global Details",
    code: 13,
  },
  FETCH_ORDERS: { reqTitle: "Fetch Orders", code: 14 },
  GET_STARTER_SETTINGS: { reqTitle: "get starter settings", code: 15 },
  GET_FIREBASE_SETTINGS_REQUEST: {
    reqTitle: "get firebase settings request",
    code: 16,
  },
  GET_CUSTOMER_INFO: { reqTitle: "get customer info", code: 17 },
  START_TALKING: { reqTitle: "Start Talking", code: 18 },
  APPLY_COUPON_REQUEST: { reqTitle: "apply coupon request", code: 19 },
  GET_CALLS: { reqTitle: "Get Calls", code: 20 },
  SEND_MESSAGE: { reqTitle: "Send Message", code: 21 },
  WATCH_CHANNEL: { reqTitle: "Watch Channel", code: 22 },
  DELETE_MESSAGE: { reqTitle: "Delete Message", code: 23 },
  DELETE_CHANNEL: { reqTitle: "Delete Channel", code: 24 },
  CURRENCY_REQUEST: { reqTitle: "Currency Request", code: 25 },
  GETORDERBYORDERGROUPID_REQUEST: {
    reqTitle: "getOrderByOrderGroupID request",
    code: 26,
  },
  OLD_CART_REQUEST: { reqTitle: "Old Cart Request", code: 27 },
  CART_REQUEST: { reqTitle: "Cart Request", code: 28 },
  CART_OVERVIEW: { reqTitle: "Cart Oreview", code: 29 },
  VIDEO_CALL: { reqTitle: "Video Call", code: 30 },
  VOICE_CALL: { reqTitle: "Voice Call", code: 31 },
  ANSWER_CALL: { reqTitle: "Answer Call", code: 32 },
  AGORA_TOKEN: { reqTitle: "Agora Token", code: 33 },
  IN_ANOTHER_CALL: { reqTitle: "In Another Call", code: 34 },
  END_CALL: { reqTitle: "End Call", code: 35 },
  REFUSE_CALL: { reqTitle: "Refuse Call", code: 36 },
  RECIEIVE_CHANNEL: { reqTitle: "Recieve Channel", code: 107 },
  GET_MESSAGES_OF_CHANNEL: {
    reqTitle: "Get Messages Of Channel",
    code: 38,
  },
  SEARCH_MESSAGE: { reqTitle: "Search Message", code: 39 },
  PIN_CHANNEL: { reqTitle: "Pin Channel", code: 40 },
  MUTE_CHANNEL: { reqTitle: "Mute Channel", code: 41 },
  GET_MESSAGES_OF_CHANNEL_2: {
    reqTitle: "Get Messages of Channel",
    code: 42,
  },
  GET_CONTACTS: { reqTitle: "Get Contacts", code: 43 },
  GET_MEDIA_FOR_A_CHANNEL: {
    reqTitle: "get Media for a Channel",
    code: 44,
  },
  GET_CHANNEL_DATA: { reqTitle: "Get Channel Data", code: 45 },
  GET_STORIES: { reqTitle: "Get Stories", code: 46 },
  LOGIN_STORIES: { reqTitle: "Login Stories", code: 47 },
  INCREASE_VIEWERS: { reqTitle: "Increase Viewers", code: 48 },
  UPLOAD_STORY: { reqTitle: "Upload Story", code: 49 },
  DELETE_STORY: { reqTitle: "Delete Story", code: 50 },
  GET_STORIES_FOR_PRODUCTS: {
    reqTitle: "Get Stories for Products",
    code: 51,
  },
  GET_TRENDING_SEARCH: { reqTitle: "Get Trending Search", code: 52 },
  GET_SEARCH_OPTIONS: { reqTitle: "Get Search Options", code: 53 },
  PAY_ORDER: { reqTitle: "pay Order", code: 54 },
  GET_WALLET: { reqTitle: "Get Wallet", code: 55 },
  GET_ADDRESS_LIST: { reqTitle: "Get Address List", code: 56 },
  SET_DEFAULT_ADDRESS: { reqTitle: "set default Address", code: 57 },
  ADD_ADDRESS: { reqTitle: "Add Address", code: 58 },
  UPDATE_ADDRESS: { reqTitle: "Update Address", code: 59 },
  DELETE_ADDRESS: { reqTitle: "Delete Address", code: 60 },
  GET_PROVINCES: { reqTitle: "Get Provinces", code: 61 },
  CANCEL_ORDER: { reqTitle: "Cancel Order", code: 62 },
  CANCEL_ORDER_ITEM: { reqTitle: "Cancel Order Item", code: 63 },
  CHANGE_ORDER_ADDRESS: { reqTitle: "Change Order Address", code: 64 },
  FETCH_NOTIFICATIONS: { reqTitle: "Fetch Notifications", code: 65 },
  FETCH_NOTIFICATIONS_TYPES: {
    reqTitle: "Fetch Notifications Types",
    code: 66,
  },
  REGISTER_DEVICE_FOR_EXPIRED_USER: {
    reqTitle: "register device for expired user",
    code: 67,
  },
  "REGISTER_DEVICE_FOR_EXPIRED_USER_-_RETRY": {
    reqTitle: "register device for expired user - retry",
    code: 68,
  },
  REGISTER_FIREBASE_TOKEN: {
    reqTitle: "register firebase token",
    code: 69,
  },
  REGISTER_DEVICE: { reqTitle: "register device", code: 70 },
  STORE_FIREBASE_SUBSCRIBE_TOPIC: {
    reqTitle: "store firebase subscribe topic",
    code: 71,
  },
  STORE_FIREBASE_UNSUBSCRIBE_TOPIC: {
    reqTitle: "store firebase unsubscribe topic",
    code: 72,
  },
  "CHANGE_FIREBASE_COUNTRY-LANGUAGE_PAIR": {
    reqTitle: "change firebase country-language pair",
    code: 73,
  },
  HIDE_OLD_CART: { reqTitle: "Hide Old Cart", code: 74 },
  SEND_BOUTIQUE_CREATED: { reqTitle: "send boutique created", code: 75 },
  SEND_PRODUCT_CART_EXPIRATION: {
    reqTitle: "send product cart expiration",
    code: 76,
  },
  SEND_PRODUCT_AVAILABILITY: {
    reqTitle: "send product availability",
    code: 77,
  },
  SEND_PRODUCT_COMMENT: { reqTitle: "send product comment", code: 78 },
  SEND_PRODUCT_DISCOUNT: { reqTitle: "send product discount", code: 79 },
  SEND_CATEGORY_CREATED: { reqTitle: "send category created", code: 80 },
  SEND_PRODUCT_BEFORE_STOCK_OUT: {
    reqTitle: "send product before stock out",
    code: 81,
  },
  SEND_PRODUCT_WHEN_CHANGE_IN_PRICE: {
    reqTitle: "send product when change in price",
    code: 82,
  },
  EDIT_NOTIFICATION_SETTINGS: {
    reqTitle: "edit notification settings",
    code: 83,
  },
  LOGIN_CHAT: { reqTitle: "Login Chat", code: 84 },
  SHARE_PRODUCT: { reqTitle: "Share Product", code: 85 },
  STORE_TOKEN: { reqTitle: "Store Token", code: 86 },
  GET_CHATS: { reqTitle: "Get Chats", code: 87 },
  GET_PRODUCT_VARIANTS: { reqTitle: "Get Product Variants", code: 88 },
  CONVERT_TO_OLD_CART: { reqTitle: "Convert to Old Cart", code: 89 },
  SEND_OTP: { reqTitle: "Send OTP", code: 90 },
  VERIFY_OTP: { reqTitle: "Verify OTP", code: 91 },
  UPDATE_NAME_IN_MARKET: { reqTitle: "Update Name in market", code: 92 },
  UPDATE_NAME_IN_CHAT: { reqTitle: "Update Name in chat", code: 93 },
  UPDATE_NAME_IN_STORIES: {
    reqTitle: "Update Name in stories",
    code: 94,
  },
  UPDATE_PROFILE: { reqTitle: "Update Profile", code: 95 },
  UPDATE_PROFILE_IMAGE: { reqTitle: "Update Profile Image", code: 96 },
  GET_CHAT_WITH_DELEIVERY: {
    reqTitle: "Get Chat with Deleivery",
    code: 98,
  },
  SOCIAL_INFO_REQUEST: { reqTitle: "Social Info Request", code: 99 },
  "LIKE_&_COMMENTS_DATA_REQUEST": {
    reqTitle: "Like & Comments Data Request",
    code: 100,
  },
  GET_CURRENCY: { reqTitle: "Get Currency", code: 101 },
  ADD_TO_CART_WIDGET: { reqTitle: "Add to cart widget", code: 102 },
  ADD_TO_CART: { reqTitle: "Add To Cart", code: 103 },
  UPDATE_CART_ITEM: { reqTitle: "Update Cart Item", code: 104 },
  REMOVE_FROM_CART: { reqTitle: "Remove From Cart", code: 105 },
  GET_LAST_SEEN: { reqTitle: "Get Last Seen", code: 106 },
  COUNTRY_MAP_BORDERS: { reqTitle: "Country Map Boundaries", code: 107 },
  GETORDERSBYCARTGROUPID: { reqTitle: "getOrdersByCartGroupID", code: 108 },
  GET_ADDRESS_BY_TEXT: { reqTitle: "Get Address By Text", code: 109 },
  UPLOAD_CHAT_FILE: { reqTitle: "UPLOAD_CHAT_FILE", code: 110 },
  SAVE_CONTACTS: { reqTitle: "SAVE_CONTACTS", code: 111 },
  CHANNEL_SERACH: { reqTitle: "CHANNEL_SERACH", code: 112 },
  GET_USER_STORIES: { reqTitle: "GET_USER_STORIES", code: 113 },
  ADD_COMMENT_FOR_PRODUCT: { reqTitle: "ADD_COMMENT_FOR_PRODUCT", code: 114 },
  RESEND_COMMENT: { reqTitle: "RESEND_COMMENT", code: 115 },
  GET_VIEW_PRODUCT: { reqTitle: "GET_VIEW_PRODUCT", code: 116 },
  COMMENT_DATA_REQUEST: { reqTitle: "COMMENT_DATA_REQUEST", code: 117 },
  LIKE_FOR_PRODUCT: { reqTitle: "LIKE_FOR_PRODUCT", code: 118 },
  UNLIKE_PRODUCT: { reqTitle: "UNLIKE_PRODUCT", code: 119 },
  SHARE_SOCIAL: { reqTitle: "SHARE_SOCIAL", code: 120 },
  VERIFY_OTP_FROM_GUEST: { reqTitle: "VERIFY_OTP_FROM_GUEST", code: 121 },
  CHANGE_ORDER_VARIANT: { reqTitle: "CHANGE_ORDER_VARIANT", code: 122 },
  REPORT_STORY: { reqTitle: "REPORT_STORY", code: 123 },
  RATE_ORDER_DETAILS: { reqTitle: "RATE_ORDER_DETAILS", code: 124 },
  UPDATE_ORDER_RATE: { reqTitle: "UPDATE_ORDER_RATE", code: 125 },
  UPLOAD_CLOUDINARY: { reqTitle: "UPLOAD_CLOUDINARY", code: 126 },
  RETURN_REASONS: { reqTitle: "RETURN_REASONS", code: 127 },
  RETURN_PRODUCT: { reqTitle: "RETURN_PRODUCT", code: 128 },
  CANCEL_RETURN_PRODUCT: { reqTitle: "CANCEL_RETURN_PRODUCT", code: 129 },
  UPDATE_RETURN_PRODUCT: { reqTitle: "UPDATE_RETURN_PRODUCT", code: 130 },
  CREAT_RETURN_REQ: { reqTitle: "CREAT_RETURN_REQ", code: 131 },
  VIEW_RETURN_PRODUCT: { reqTitle: "VIEW_RETURN_PRODUCT", code: 132 },
  CONFIRM_RETURN_PRODUCT: { reqTitle: "CONFIRM_RETURN_PRODUCT", code: 133 },
  DETAILS_RETURN_PRODUCT: { reqTitle: "DETAILS_RETURN_PRODUCT", code: 134 },
  CANCEL_RETURN_REQ: { reqTitle: "CANCEL_RETURN_REQ", code: 135 },
  REMOVE_IMAGE: { reqTitle: "REMOVE_IMAGE", code: 136 },
  GET_RECOMENDATIONS: { reqTitle: "GET_RECOMENDATIONS", code: 137 },
  GET_ORDER_RATING: { reqTitle: "GET_ORDER_RATING", code: 138 },
  UPDATE_COMMENT: { reqTitle: "UPDATE_COMMENT", code: 139 },
  DELETE_COMMENT: { reqTitle: "DELETE_COMMENT", code: 140 },
  LIKE_FOR_COMMENT: { reqTitle: "LIKE_FOR_COMMENT", code: 141 },
  UNLIKE_FOR_COMMENT: { reqTitle: "UNLIKE_FOR_COMMENT", code: 142 },
  GET_SHOPES_FOR_SELLER: { reqTitle: "GET_SHOPES_FOR_SELLER", code: 143 },
  GET_ORDER_DETAILS: { reqTitle: "GET_ORDER_DETAILS", code: 144 },
  GET_SELLER_PRODUCTS: { reqTitle: "GET_SELLER_PRODUCTS", code: 145 },
  GET_SELLER_BOUTIQUES: { reqTitle: "GET_SELLER_BOUTIQUES", code: 146 },
  GET_SELLER_PERMISSIONS: { reqTitle: "GET_SELLER_PERMISSIONS", code: 147 },
  GET_SHOP_ROLES: { reqTitle: "GET_SHOP_ROLES", code: 148 },
  ADD_USER_TO_SHOP: { reqTitle: "ADD_USER_TO_SHOP", code: 149 },
  GET_SELLER_ORDERS: { reqTitle: "GET_SELLER_ORDERS", code: 150 },
  UPDATE_SELLER_ORDER_STATUS: { reqTitle: "UPDATE_SELLER_ORDER_STATUS", code: 151 },
};
