import "styles/globals.css";
import "styles/calls.css";
export const metadata = {
  title: "TryDos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className="bg-black">{children}</body>
    </html>
  );
}
