import '../../../components/Chat/components/index.css'
import '../../../components/Chat/components/styles.css'
import '../../globals.css'
export const metadata = {
  title: 'TryDos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
  
           {children}
     
        </body>
    

    </html>
  )
}
